### PR TITLE
Seperate out clock arguments from product types

### LINKED ISSUE #477: Unexpected glitch in RTL-level simulation due to clock assignements
With CLaSH 949a05a1d8b1e4b3aabf224248c3e0e124c8fc39 the behavior of the following code is quite strange in at least the Intel/Altera ModelSim:

```
i2cMaster
    :: forall domain gated synchronous. (HiddenClockReset domain gated synchronous)
    => Word32 -> Signal domain Bit
i2cMaster halfDiv = scl
  where
    phase = regEn (0 :: Unsigned 2) (countTo halfDiv) (phase + 1)
    scl = boolToBit . (\phi -> any (== phi) [0, 1]) <$> phase
```

with this version, the RTL-level simulation of `SCL` produces a waveform containing a 1ps glitch at time 360001 (and then repeated at later times): https://gist.github.com/gergoerdi/07d601acbf28d46ae6e9b2d6399a58d1#file-eq_phi-vcd

If I replace the definition of `scl` with

```
    scl = boolToBit . (\phi -> any (phi ==) [0, 1]) <$> phase
```

then there is no glitch visible in the waveform: https://gist.github.com/gergoerdi/07d601acbf28d46ae6e9b2d6399a58d1#file-phi_eq-vcd

### PR DESCRIPTION
**Pull request by christiaanb**
Turns e.g.

```    
f :: (Clock System, Reset System) -> Signal System Int
```

into    

``` 
f :: Clock System -> Reset System -> Signal System Int
```

We need this because HDL synthesis tools don't like it when clocks and resets end up in structs or bitvectors, which product types are usually mapped to. This also solves an annoyance in VHDL where we had to delay register assignment by 1ps to avoid delta-cycle weirdness.
    
Fixes #477
Partially solves #418

### CODE REVIEW

File: clash-lib/src/Clash/Core/Util.hs [hunk 1]
```diff
@@ -932,3 +933,73 @@ tySym
...
+  = if any (\ty -> isJust (shouldSplit0 tcm ty) || splitTy ty) dcArgVs then
+      Just (mkApps (Data dc) (map Right tyArgs), dcArgs)
+    else
+      Nothing
+ where
+  -- Currently we're only interested in splitting of Clock, Reset, and Enable
+  splitTy (TyConApp tcNm0 _)
+    = nameOcc tcNm0 `elem` [ "Clash.Signal.Internal.Clock"
+                           , "Clash.Signal.Internal.Reset"
+                           , "Clash.Signal.Internal.Enable"
```
Comment (martijnbastiaan) [inline clash-lib/src/Clash/Core/Util.hs]: Are enable lines special in Verilog/VHDL?

Comment (christiaanb) [reply clash-lib/src/Clash/Core/Util.hs]: No, just like clock and reset aren't. However, ASIC synthesis tools derive clock gating from enables, so let's make sure they can do their job as easy as possible.

Comment (martijnbastiaan) [reply clash-lib/src/Clash/Core/Util.hs]: Right, makes sense.

**Comment by blaxill** [comment]
@christiaanb does this automatically work for result product types e.g. https://github.com/clash-lang/clash-compiler/blob/6a822937ca5bac2e78f968d162fd1d068137f217/clash-lib/src/Clash/Primitives/Intel/ClockGen.hs#L74

Where `InstDecl` result assignment is a `DataCon` of potentially Clocks and Signals or is this case unhandled? I'm currently using the `DataCon` method for #850

**Comment by christiaanb** [comment]
@blaxill No... although there's logic in https://github.com/clash-lang/clash-compiler/pull/815 that does that. I can separate it out and add it to this PR.

**Comment by martijnbastiaan** [comment]
@leonschoorl This PR is pending your review. Are you happy with it?
