### PR TITLE
The (initial) content for all blockRam's and rom's must be constant. Fix #331

### LINKED ISSUE #331: BlockRam initialisation on Verilog not executing properly.
Initialising a blockRam in Clash gives the following output - 

```
// blockRam begin                                                                                                                                            
  reg signed [31:0] RAM [0:128-1];                                                                                                                             
                                                                                                                                                               
  reg [4095:0] ram_init;                                                                                                                                       
  integer i;                                                                                                                                                   
  initial begin                                                                                                                                                
    ram_init = xs;                                                                                                                                             
    for (i=0; i < 128; i = i + 1) begin                                                                                                                        
      RAM[128-1-i] = ram_init[i*32+:32];                                                                                                                       
    end                                                                                                                                                        
  end                                                                                                                                                          
                                                                                                                                                               
  always @(posedge CLK) begin                                                                                                                                  
      ram_init <= xs;                                                                                                                                          
  end                                                                                                                                                          
                                                                                                                                                               
  always @(posedge CLK) begin : memElement_blockRam                                                                                                            
    if (\#app_arg ) begin                                                                                                                                      
      RAM[(wild_0)] <= y;                                                                                                                                      
    end                                                                                                                                                        
    RD_DATA <= RAM[(wild)];                                                                                                                                    
  end                                                                                                                                                          
  // blockRam end
```

But as can be seen in this part, 
```
initial begin                                                                                                                                                
    ram_init = xs;                                                                                                                                             
    for (i=0; i < 128; i = i + 1) begin                                                                                                                        
      RAM[128-1-i] = ram_init[i*32+:32];                                                                                                                       
    end                                                                                                                                                        
  end 
```
The initial value of wires is always z (High impedance), thus for Verilog Simulators, this does not work as subsequent cycles all have the value of RAM instantiated to z.

One possible solution is to add this code
```
always @(posedge clock) begin
    ram_init <= xs;
end
```

Could anyone comment on this? I am using iVerilog on my machine, simulation using vvp and plotting the signal output using GTKwave.

### PR DESCRIPTION
**Pull request by leonschoorl**
Fixes #331

### CODE REVIEW

**Comment by leonschoorl** [comment]
We should look into providing a nicer error when the initial content is not constant.

Because right now it produces a scary and not very helpful:
```
clash: panic! (the 'impossible' happened)
  (GHC version 8.4.3 for x86_64-unknown-linux):
	Clash.Netlist.BlackBox(122): Forced to evaluate untranslatable type: (Clash.Transformations.removedArg
  @GHC.Stack.Types.CallStack :: GHC.Stack.Types.CallStack)
CallStack (from HasCallStack):
  error, called at src/Clash/Netlist/BlackBox.hs:122:30 in clash-lib-0.99-inplace:Clash.Netlist.BlackBox

```

File: clash-lib/src/Clash/Netlist/BlackBox.hs [hunk 1]
```diff
@@ -119,8 +119,10 @@ mkArgument bndr e = do
     let eTyMsg = "(" ++ showDoc e ++ " :: " ++ showDoc ty ++ ")"
     ((e',t,l),d) <- case hwTyM of
       Nothing   ->
-        return ((Identifier (error ($(curLoc) ++ "Forced to evaluate untranslatable type: " ++ eTyMsg)) Nothing
-                ,Void Nothing,False),[])
+        let identifier = case findRemovedArg e of
```
Comment (christiaanb) [inline clash-lib/src/Clash/Netlist/BlackBox.hs]:
```haskell
Nothing
  | (Prim nm _,_) <- collectArgs e
  , nm == "Clash.Transformations.removedArgs"
  -> return (Identifier (Text.fromString nm) Nothing, Void Nothing, False),[])
  | otherwise
  -> error ("Forced to evaluate untranslatable type: " ++ eTyMsg)
```

**Comment by martijnbastiaan** [comment]
@leonschoorl Could you comment on the status of this PR? It seems that you've incorporated Christiaan's suggestions and that it's ready to merge?
