### PR TITLE
`~ISUNDEFINED` for `BitVector` and product types

### LINKED ISSUE #2117: -fclash-aggressive-x-optimization-blackboxes does not work on `deepErrorX` of `BitVector`
The following code generates a reset on the data when compiled with `clash -fclash-aggressive-x-optimization-blackboxes --vhdl`:
```haskell
import           Clash.Explicit.Prelude

topEntity
  :: Clock XilinxSystem
  -> Reset XilinxSystem
  -> Enable XilinxSystem
  -> Signal XilinxSystem (BitVector 8)
  -> Signal XilinxSystem (BitVector 8)
topEntity clk rst en = register clk rst en (deepErrorX "undefined reset")
```
vhdl:
```vhdl
  -- register begin
  result_1_register : process(clk)
  begin
    if rising_edge(clk) then
      if rst =  '1'  then
        result_1 <= std_logic_vector'("--------"); -- OFFENDING LINE
      elsif en then
        result_1 <= i;
      end if;
    end if;
  end process;
  -- register end
```
Replacing `BitVector` for `Unsigned` does not have this problem.

Presumably this is because of a BitVector creates a mask not a direct `errorX` and presumably similar problems will exist with records where every field is `errorX` but the structure is defined. The intuitive fix would be to pack the data and check whether it is all undefined as opposed to relying on the Haskell representation.

### PR DESCRIPTION
**Pull request by DigitalBrains1**
Fixes #2117

## Still TODO:

  - [x] Write a changelog entry (see changelog/README.md)
  - [x] Check copyright notices are up to date in edited files

### CODE REVIEW

File: clash-lib/src/Clash/Netlist/BlackBox/Util.hs [hunk 1]
```diff
@@ -474,10 +475,19 @@ renderElem b (IF c t f) = do
...
-          _ -> 0
+        let
+          (e, _, _) = bbInputs b !! n
+          checkUndefined e0 = case e0 of
+            BlackBoxE _ _ _ _ (N.BBTemplate [Err _]) _ _ -> 1
+            BlackBoxE "Clash.Sized.Internal.BitVector.fromInteger#" [] [] [] _ bbCtx _
+              | [sz, mask, _val] <- bbInputs bbCtx
+              , (Literal _ (NumLit sz0), _, True) <- sz
+              , (Literal _ (NumLit mask0), _, True) <- mask
+              , mask0 == (1 `shiftL` fromInteger sz0) - 1
```
Comment (martijnbastiaan) [inline clash-lib/src/Clash/Netlist/BlackBox/Util.hs:486]: Perhaps

```suggestion
              , mask0 == 2^sz0 - 1
```

File: clash-lib/src/Clash/Netlist/BlackBox/Util.hs [hunk 2]
```diff
@@ -474,10 +475,19 @@ renderElem b (IF c t f) = do
                       _            -> 0
 
       (IsUndefined n) ->
-        let (e, _, _) = bbInputs b !! n in
-        case (xOpt, e) of
-          (True, BlackBoxE _ _ _ _ (N.BBTemplate [Err _]) _ _) -> 1
-          _ -> 0
+        let
+          (e, _, _) = bbInputs b !! n
+          checkUndefined e0 = case e0 of
```
Comment (martijnbastiaan) [inline clash-lib/src/Clash/Netlist/BlackBox/Util.hs:480]: Perhaps

```suggestion
          checkUndefined = \case
```

Comment (martijnbastiaan) [reply clash-lib/src/Clash/Netlist/BlackBox/Util.hs:480]: I think `checkUndefined` is a very nice function to have on top-level too! I'm sure it'll come in handy somewhere else in the future.

File: tests/shouldwork/BlackBox/T2117.hs [hunk 3]
```diff
@@ -0,0 +1,83 @@
...
+  :: NFDataX a
+  => a
+  -> Signal System Bool
+testUndefined !_ = pure True
+{-# NOINLINE testUndefined #-}
+{-# ANN testUndefined (InlinePrimitive [VHDL] $ unindent [i|
+  [ { "BlackBox" :
+      { "name"      : "T2117.testUndefined"
+      , "kind"      : "Expression"
+      , "template"  : "~IF ~ISUNDEFINED[1] ~THEN true ~ELSE false ~FI"
```
Comment (martijnbastiaan) [inline tests/shouldwork/BlackBox/T2117.hs:61]: Clever!

**Review by martijnbastiaan — APPROVED** [review]
LGTM

File: clash-lib/src/Clash/Netlist/BlackBox/Util.hs (hunk 2 above)
Comment (DigitalBrains1) [reply clash-lib/src/Clash/Netlist/BlackBox/Util.hs]: Done!

**Review by martijnbastiaan — APPROVED** [review]
