### PR TITLE
Fix ambiguous data files on duplicate idir

### LINKED ISSUE #3141: Clash errors if it finds the same data file twice
```haskell
-- In `src/Memory.hs`
module Memory where

import Clash.Explicit.Prelude

topEntity ::
  Clock System ->
  Enable System ->
  Signal System (Unsigned 4) ->
  Signal System (Maybe (Unsigned 4, BitVector 8)) ->
  Signal System (BitVector 8)
topEntity clk ena = blockRamFile clk ena d16 "memory.bin"
```

Reproducer:

```
$ cabal run clash -- -isrc -isrc Memory --vhdl
<no location info>: error:
    Clash error call:
    Multiple data files for "memory.bin" found. The following candidates were found:
      ["src/memory.bin","src/memory.bin"]
    Please disambiguate data files.
    CallStack (from HasCallStack):
      error, called at src/Clash/Netlist/BlackBox/Util.hs:343:20 in clash-lib-1.9.0-inplace:Clash.Netlist.BlackBox.Util
```

This of course sounds silly, but passing down the same directory twice can happen more easily in build systems / generic environments.

### PR DESCRIPTION
**Pull request by TristanCacqueray**
When library and simulator code share the same hs-source-dirs, clash fails to resolve data file with the following error:
```
  Multiple data files for "font.bin" found. The following candidates were found:
    ["./font.bin","./font.bin"]
```
This change fix that bug by removing duplicated source dirs.

Fixes #3141

## Still TODO:

  - [x] Write a changelog entry (see changelog/README.md)
  - [ ] Check copyright notices are up to date in edited files

[comment]: # (Depending on the change, some of these points may not be necessary. If so, leave the boxes unchecked so it is easier for a reviewer to see what has been omitted.)

### CODE REVIEW

File: clash-lib/src/Clash/Netlist/BlackBox/Util.hs [hunk 1]
```diff
@@ -332,7 +332,7 @@ canonicalizeDataFilePath idirs toCanonicalize
       (canonicalizePath toCanonicalize)
       (error [I.i|Could not find data file #{show toCanonicalize}. Does it exist?|])
   | otherwise = unsafePerformIO $ do
-      let candidates = map (</> toCanonicalize) idirs
+      let candidates = map (</> toCanonicalize) (nub idirs)
```
Comment (martijnbastiaan) [inline clash-lib/src/Clash/Netlist/BlackBox/Util.hs]:
```suggestion
      let candidates = map (</> toCanonicalize) (nubOrd idirs)
```

`nub` is `O(n^2)`

**Review by martijnbastiaan — COMMENTED** [review]
Thanks for your PR! I'm not sure I understand:

> When library and simulator code share the same hs-source-dirs

You mean when you have a Cabal file with a `library` and `executable` (simulator) that source from the same source dir, you get this error?

File: clash-lib/src/Clash/Netlist/BlackBox/Util.hs (hunk 1 above)
Comment (TristanCacqueray) [reply clash-lib/src/Clash/Netlist/BlackBox/Util.hs]: Thanks!
