### PR TITLE
Don't quote bit literals with `-fclash-force-undefined`

### LINKED ISSUE #2360: -fclash-force-undefined produces invalid values for BitVector with undefined bits.
Title says it all I think.

Reproducer:
```haskell
module Example.Project where

import Clash.Prelude

topEntity ::(BitVector 8)
topEntity = deepErrorX "broken"

```
compiled with `cabal run -- clash --verilog Example.Project -fclash-force-undefined=0`, produces:
```verilog
/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.6.4. DO NOT MODIFY.
*/
`timescale 100fs/100fs
module topEntity
    ( // No inputs

      // Outputs
      output wire [7:0] result
    );


  assign result = 8'b'0''0''0''0''0''0''0''0'; // invalid value


endmodule
```

HDL was generated with 1.6.4, but the problem was encountered with 1.7.0.
Problem also exists for systemverilog and vhdl.

### PR DESCRIPTION
**Pull request by alex-mckenna**
When rendering bit literals, we use the `char` function from the prettyprinter in most cases. For undefined bits we were using the `int` function, and wrapping in single quotes. This is not the same: the `char` function prints a single Haskell `Char`, but does _not_ wrap that character in quotes.

Simply removing the quote marks solves the issue.

Fixes #2360.

## Still TODO:

  - [x] Write a changelog entry (see changelog/README.md)
  - [ ] ~Check copyright notices are up to date in edited files~

[comment]: # (Depending on the change, some of these points may not be necessary. If so, leave the boxes unchecked so it is easier for a reviewer to see what has been omitted.)

### CODE REVIEW

**Review by martijnbastiaan — APPROVED** [review]

File: tests/Main.hs [hunk 1]
```diff
@@ -635,6 +635,7 @@ runClashTest = defaultMain $ clashTestRoot
         , outputTest "T2325f" def{hdlTargets=[VHDL]}
         , runTest "T2342A" def{hdlSim=[]}
         , runTest "T2342B" def{hdlSim=[]}
+        , runTest "T2360" def{hdlSim=[]}
```
Comment (DigitalBrains1) [inline tests/Main.hs:638]: Shouldn't this pass `-fclash-force-undefined=0` to properly test the issue?

**Review by DigitalBrains1 — CHANGES_REQUESTED** [review]

File: tests/Main.hs (hunk 1 above)
Comment (DigitalBrains1) [reply tests/Main.hs:638]: And it also doesn't actually run it in any HDL tool? I think the problem only crops up on actual running?

Comment (alex-mckenna) [reply tests/Main.hs]: Shh, _you saw nothing_

**Review by DigitalBrains1 — APPROVED** [review]
