### PR TITLE
Handle impredicative instantiation of error values 

### LINKED ISSUE #2272: Evaluator fails impredicative type instantiation of error values
```haskell
{-# LANGUAGE ImpredicativeTypes, TypeApplications, GADTs #-}
module ImpredErr where

import Clash.Prelude

data Ex where
  ExT :: (forall a . String -> a) -> Ex

f :: Ex
f = ExT (errorX @(forall b . String -> b) "qq")
{-# NOINLINE f #-}

topEntity :: Int
topEntity = case f of
  ExT h -> h "kk"
```
fails with:
```
    Clash error call:
    Evaluator.instantiate: Not a tylambda: PrimVal (PrimInfo {primName = "Clash.XException.errorX", primType = ForAllTy (TyVar {varName = Name {nameSort = User, nameOcc = "a", nameUniq = 6989586621679042592, nameLoc = RealSrcSpan SrcSpanOneLine "Test.hs" 10 9 48}, varUniq = 6989586621679042592, varType = AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Prim.TYPE", nameUniq = 3674937295934324912, nameLoc = RealSrcSpan SrcSpanOneLine "Test.hs" 10 9 48}))) (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Types.LiftedRep", nameUniq = 3891110078048108766, nameLoc = RealSrcSpan SrcSpanOneLine "Test.hs" 10 9 48})))}) (AppTy (AppTy (ConstTy Arrow) (AppTy (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Classes.IP", nameUniq = 3602879701896396848, nameLoc = RealSrcSpan SrcSpanOneLine "Test.hs" 10 9 48}))) (LitTy (SymTy "callStack"))) (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Stack.Types.CallStack", nameUniq = 3674937295934325108, nameLoc = RealSrcSpan SrcSpanOneLine "Test.hs" 10 9 48}))))) (AppTy (AppTy (ConstTy Arrow) (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Types.[]", nameUniq = 3674937295934324788, nameLoc = RealSrcSpan SrcSpanOneLine "Test.hs" 10 9 48}))) (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Types.Char", nameUniq = 3674937295934324752, nameLoc = RealSrcSpan SrcSpanOneLine "Test.hs" 10 9 48}))))) (VarTy (TyVar {varName = Name {nameSort = User, nameOcc = "a", nameUniq = 6989586621679042592, nameLoc = RealSrcSpan SrcSpanOneLine "Test.hs" 10 9 48}, varUniq = 6989586621679042592, varType = AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Prim.TYPE", nameUniq = 3674937295934324912, nameLoc = RealSrcSpan SrcSpanOneLine "Test.hs" 10 9 48}))) (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Types.LiftedRep", nameUniq = 3891110078048108766, nameLoc = RealSrcSpan SrcSpanOneLine "Test.hs" 10 9 48})))})))), primWorkInfo = WorkConstant, primMultiResult = SingleResult, primUnfolding = Unfolding (Id {varName = Name {nameSort = User, nameOcc = "Clash.XException.errorX", nameUniq = 8214565720323787764, nameLoc = RealSrcSpan SrcSpanOneLine "Test.hs" 10 9 48}, varUniq = 8214565720323787764, varType = ForAllTy (TyVar {varName = Name {nameSort = User, nameOcc = "a", nameUniq = 6989586621679042592, nameLoc = RealSrcSpan SrcSpanOneLine "Test.hs" 10 9 48}, varUniq = 6989586621679042592, varType = AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Prim.TYPE", nameUniq = 3674937295934324912, nameLoc = RealSrcSpan SrcSpanOneLine "Test.hs" 10 9 48}))) (ConstTy (TyCon (Name {nameSort = User, 
nameOcc = "GHC.Types.LiftedRep", nameUniq = 3891110078048108766, nameLoc = RealSrcSpan SrcSpanOneLine "Test.hs" 10 9 48})))}) (AppTy (AppTy (ConstTy Arrow) (AppTy (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Classes.IP", nameUniq = 3602879701896396848, nameLoc = RealSrcSpan SrcSpanOneLine "Test.hs" 10 9 48}))) (LitTy (SymTy "callStack"))) (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Stack.Types.CallStack", nameUniq = 3674937295934325108, nameLoc = RealSrcSpan SrcSpanOneLine "Test.hs" 10 9 48}))))) (AppTy (AppTy (ConstTy Arrow) (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Types.[]", nameUniq = 3674937295934324788, nameLoc = RealSrcSpan SrcSpanOneLine "Test.hs" 10 9 48}))) (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Types.Char", nameUniq = 3674937295934324752, nameLoc = RealSrcSpan SrcSpanOneLine "Test.hs" 10 9 48}))))) (VarTy (TyVar {varName = Name {nameSort = User, nameOcc = "a", nameUniq = 6989586621679042592, nameLoc = RealSrcSpan SrcSpanOneLine "Test.hs" 10 9 48}, varUniq = 6989586621679042592, varType = AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Prim.TYPE", nameUniq = 3674937295934324912, nameLoc = RealSrcSpan SrcSpanOneLine "Test.hs" 10 9 48}))) (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Types.LiftedRep", nameUniq = 3891110078048108766, nameLoc = RealSrcSpan SrcSpanOneLine "Test.hs" 10 9 48})))})))), idScope = GlobalId})}) [ForAllTy (TyVar {varName = Name {nameSort = User, nameOcc = "b", nameUniq = 6989586621679042239, nameLoc = RealSrcSpan SrcSpanOneLine "Test.hs" 10 26 27}, varUniq = 6989586621679042239, varType = AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Prim.TYPE", nameUniq = 3674937295934324912, nameLoc = RealSrcSpan SrcSpanOneLine "Test.hs" 10 9 48}))) (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Types.LiftedRep", nameUniq = 3891110078048108766, nameLoc = RealSrcSpan SrcSpanOneLine "Test.hs" 10 9 48})))}) (AppTy (AppTy (ConstTy Arrow) (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Types.[]", nameUniq = 3674937295934324788, nameLoc = RealSrcSpan SrcSpanOneLine "Test.hs" 10 9 48}))) (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Types.Char", nameUniq = 3674937295934324752, nameLoc = RealSrcSpan SrcSpanOneLine "Test.hs" 10 9 48}))))) (VarTy (TyVar {varName = Name {nameSort = User, nameOcc = "b", nameUniq = 6989586621679042239, 
nameLoc = RealSrcSpan SrcSpanOneLine "Test.hs" 10 26 27}, varUniq = 6989586621679042239, varType = AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Prim.TYPE", nameUniq = 3674937295934324912, nameLoc = RealSrcSpan SrcSpanOneLine "Test.hs" 10 9 48}))) (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Types.LiftedRep", nameUniq = 3891110078048108766, nameLoc = RealSrcSpan SrcSpanOneLine "Test.hs" 10 9 48})))})))] [Suspend (TyApp (Prim (PrimInfo {primName = "Clash.Normalize.Primitives.removedArg", primType = ForAllTy (TyVar {varName = Name {nameSort = System, nameOcc = "a", nameUniq = 0, nameLoc = UnhelpfulSpan "<no location info>"}, varUniq = 0, varType = ConstTy (TyCon (Name {nameSort = System, nameOcc = "Type", nameUniq = 3674937295934324910, nameLoc = UnhelpfulSpan "<no location info>"}))}) (VarTy (TyVar {varName = Name {nameSort = System, nameOcc = "a", nameUniq = 0, nameLoc = UnhelpfulSpan "<no location info>"}, varUniq = 0, varType = ConstTy (TyCon (Name {nameSort = System, nameOcc = "Type", nameUniq = 3674937295934324910, nameLoc = UnhelpfulSpan "<no location info>"}))})), primWorkInfo = WorkNever, primMultiResult = SingleResult, primUnfolding = NoUnfolding})) (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Stack.Types.CallStack", nameUniq = 3674937295934325108, nameLoc = RealSrcSpan SrcSpanOneLine "Test.hs" 10 9 48})))),Suspend (TyApp (Prim (PrimInfo {primName = "Clash.Normalize.Primitives.removedArg", primType = ForAllTy (TyVar {varName = Name {nameSort = System, nameOcc = "a", nameUniq = 0, nameLoc = UnhelpfulSpan "<no location info>"}, varUniq = 0, 
varType = ConstTy (TyCon (Name {nameSort = System, nameOcc = "Type", nameUniq = 3674937295934324910, nameLoc = UnhelpfulSpan "<no location info>"}))}) (VarTy (TyVar {varName = Name {nameSort = System, 
nameOcc = "a", nameUniq = 0, nameLoc = UnhelpfulSpan "<no location info>"}, varUniq = 0, varType = ConstTy (TyCon (Name {nameSort = System, nameOcc = "Type", nameUniq = 3674937295934324910, nameLoc = UnhelpfulSpan "<no location info>"}))})), primWorkInfo = WorkNever, primMultiResult = SingleResult, primUnfolding = NoUnfolding})) (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Types.[]", nameUniq = 3674937295934324788, nameLoc = RealSrcSpan SrcSpanOneLine "Test.hs" 10 9 48}))) (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Types.Char", nameUniq = 3674937295934324752, nameLoc 
= RealSrcSpan SrcSpanOneLine "Test.hs" 10 9 48})))))]
    CallStack (from HasCallStack):
      error, called at src-ghc\\Clash\\GHC\\Evaluator.hs:348:23 in clash-ghc-1.7.0-inplace:Clash.GHC.Evaluator
```

### PR DESCRIPTION
**Pull request by christiaanb**
Fixes #2272 

## Still TODO:

  - [x] Write a changelog entry (see changelog/README.md)
  - [x] Check copyright notices are up to date in edited files

### CODE REVIEW

File: tests/Main.hs [hunk 1]
```diff
@@ -599,9 +599,10 @@ runClashTest = defaultMain $ clashTestRoot
             , buildTargets=BuildSpecific["top_bit", "top_bitvector", "top_index", "top_signed", "top_unsigned"]
             }
         , runTest "T2046B" def{clashFlags=["-Werror"]}
-        , runTest "T2046C" def{hdlSim=[],clashFlags=["-Werror"],buildTargets=BuildSpecific["topEntity"]}
-        , runTest "T2097" def{hdlSim=[]}
-        , runTest "T2154" def{hdlTargets=[VHDL], hdlSim=[]}
+        , runTest "T2046C" def{hdlSim=False,clashFlags=["-Werror"],buildTargets=BuildSpecific["topEntity"]}
+        , runTest "T2097" def{hdlSim=False}
+        , runTest "T2154" def{hdlTargets=[VHDL], hdlSim=False}
+        , runTest "T2272" def{hdlTargets=[VHDL], hdlSim=False}
```
Comment (DigitalBrains1) [inline tests/Main.hs:605]: `hdlSim` is a list of simulators to run since PR #2257. So the existing lines were correct and the new one needs `hdlSim=[]` as well.

Comment (christiaanb) [reply tests/Main.hs:605]: Yeah, seems like I messed up my rebase.

File: clash-ghc/src-ghc/Clash/GHC/Evaluator.hs [hunk 2]
```diff
@@ -339,11 +339,13 @@ instantiate _tcm (TyLambda x e) ty m =
...
   subst0 = mkSubst iss0
   iss0   = mkInScopeSet (freeVarsOf e `unionUniqSet` freeVarsOf ty)
-instantiate tcm pVal@(PrimVal (PrimInfo{primType}) tys []) ty m
+instantiate tcm pVal@(PrimVal (PrimInfo{primType}) tys es) ty m
   | isUndefinedXPrimVal pVal
-  = setTerm (TyApp (Prim NP.undefinedX) (piResultTys tcm primType (tys ++ [ty]))) m
+  = setTerm (TyApp (Prim NP.undefinedX) (piResultTys tcm primType (tys ++ esTys ++ [ty]))) m
   | isUndefinedPrimVal pVal
-  = setTerm (TyApp (Prim NP.undefined) (piResultTys tcm primType (tys ++ [ty]))) m
+  = setTerm (TyApp (Prim NP.undefined) (piResultTys tcm primType (tys ++ esTys ++ [ty]))) m
```
Comment (martijnbastiaan) [inline clash-ghc/src-ghc/Clash/GHC/Evaluator.hs:346]: Maybe it's just because I haven't really worked on the evaluator, but I find this really difficult to read. The function's documentation doesn't really help me either. Given that it's under-documented as is, I wouldn't be opposed to merging this, but it would be great if you could add a comment anyway.

**Review by martijnbastiaan — APPROVED** [review]
Will 2022 be the year of proper Windows support? :-)
