### PR TITLE
Make applyDebug's free variable check take the context into account

### LINKED ISSUE #2623: caseCon introduces free variables because of evaluator changes
```haskell
topEntity = foo @System

foo :: forall dom. Signal dom (Vec 1 (Signed 2)) -> Signal dom Bool
foo = \input ->
    let
      scs :: Signal dom (Vec 1 Bool)
      scs = bundle $ map f $ unbundle input
    in
      fmap bar scs


bar :: (KnownNat n) => Vec (n+1) Bool -> Bool
bar = fold (&&) . map (id)

f :: Signal dom a -> Signal dom Bool
f = const $ pure $ True

```

When compiled with `-fclash-debug-invariants` (`DebugSilent` or higher) this crashes with:
```
    Clash error call:
    Clash.Rewrite.Util(226): Error when applying rewrite caseCon to:
    case Clash.Sized.Vector.map @GHC.Types.Bool[3674937295934324744]
           @GHC.Types.Bool[3674937295934324744]
           @(GHC.TypeNats.+[3674937295934325540] 0 1)
           (GHC.Base.id[8214565720323788222][GlobalId]
              @GHC.Types.Bool[3674937295934324744])
           x[6989586621679027447][LocalId] of
      Clash.Sized.Vector.Cons[8214565720323790062] m[12]
        (_co_[7] :: GHC.Prim.~#[3674937295934324842]
                      GHC.Num.Natural.Natural[3674937295934324786]
                      GHC.Num.Natural.Natural[3674937295934324786]
                      1
                      (GHC.TypeNats.+[3674937295934325540] 0 1))
          (el[6] :: GHC.Types.Bool[3674937295934324744])
          (rest[14] :: Clash.Sized.Vector.Vec[8214565720323790059]
                         0
                         GHC.Types.Bool[3674937295934324744]) ->
        el[6][LocalId]
    Result:
    let
      el[18] :: GHC.Types.Bool[3674937295934324744]
      = (λ(x[8214565720323804840] :: GHC.Types.Bool[3674937295934324744]) ->
          x[8214565720323804840][LocalId])
          ((λ(ds[6341068275337658375] :: Clash.Signal.Internal.Signal[8214565720323790017]
                                           "System"
                                           (Clash.Sized.Internal.Signed.Signed[8214565720323790051] 2)) ->
             Main.f_x[8214565720323803592][GlobalId] @"System")
             (Clash.Sized.Vector.head @0
                @(Clash.Sized.Internal.Signed.Signed[8214565720323790051] 2)
                ds[6341068275337658369][LocalId]))
    in el[18][LocalId]
    It introduces free variables.
    Before: x[6989586621679027447] :: Clash.Sized.Vector.Vec[8214565720323790059]
                                (GHC.TypeNats.+[3674937295934325540] 0 1)
                                GHC.Types.Bool[3674937295934324744]
    After: ds[6341068275337658369] :: Clash.Signal.Internal.Signal[8214565720323790017]
                                 "System"
                                 (Clash.Sized.Vector.Vec[8214565720323790059]
                                    1
                                    (Clash.Sized.Internal.Signed.Signed[8214565720323790051] 2))
    CallStack (from HasCallStack):
      error, called at src/Clash/Rewrite/Util.hs:226:15 in clash-lib-1.9.0-inplace:Clash.Rewrite.Util
```
The problem is that since [Give evaluator acces to inscope let-bindings #2571](https://github.com/clash-lang/clash-compiler/pull/2571) the evaluator has access to the let bindings, and they may reference new free variables.

In this case it looks like:
```haskell
\ds[6341068275337658369] ->
  let x[6989586621679027447] = ... ds[6341068275337658369] ...
  in .................. case map id x[6989586621679027447] of ...
                    --  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  term being rewritten
```
The evaluator transforms this into some transformed form of `x` which contains `ds`, and then `checkDebug` complains there is now a new free variable in the expression: `ds`

### PR DESCRIPTION
**Pull request by leonschoorl**
Fixes #2623

## Still TODO:

  - [ ] Write a changelog entry (see changelog/README.md)
  - [x] Check copyright notices are up to date in edited files

### CODE REVIEW

File: clash-lib/src/Clash/Rewrite/Util.hs [hunk 1]
```diff
@@ -266,6 +272,17 @@ applyDebug name exprOld hasChanged exprNew = do
...
     after  = showPpr exprNew
 
+-- NOTE [Filter free variables]
+-- Since [Give evaluator acces to inscope let-bindings #2571](https://github.com/clash-lang/clash-compiler/pull/2571)
+-- the evaluator can rewrite expressions using let bindings from the 'TransformContext',
+-- these bindings may reference other things bound in the context which weren't
+-- in the expression before, and in doing so introduces new free variables and
+-- fails this check for new free variables.
+-- To prevent this we filter out all variables from bound in the context.
+-- But only during a caseCon transformation, to not weaken this check unnecessarily.
```
Comment (martijnbastiaan) [inline clash-lib/src/Clash/Rewrite/Util.hs:282]:
```suggestion
-- Since [Give evaluator acces to inscope let-bindings #2571](https://github.com/clash-lang/clash-compiler/pull/2571)
-- the evaluator can rewrite expressions using let bindings from the 'TransformContext'.
-- These bindings may reference other things bound in the context which weren't
-- in the expression before, and in doing so introduces new free variables. Consequently,
-- this fails a check that prevents new free variables from being introduced -
-- as this is a bug in all other cases. To prevent this we filter out all
-- variables from bound in the context. We only do this during a 'caseCon' transformation,
-- to not weaken this check unnecessarily.
```

I've reformatted / broke up sentences to make it easier to read.

I'm not sure about this though:

> We only do this during a 'caseCon' transformation,
> to not weaken this check unnecessarily.

Is this because the evaluator is only called in `caseCon`?

**Review by martijnbastiaan — APPROVED** [review]
LGTM in general! Reformat of comment + question about it in the comments.

File: clash-lib/src/Clash/Rewrite/Util.hs (hunk 1 above)
Comment (martijnbastiaan) [reply clash-lib/src/Clash/Rewrite/Util.hs:282]: @christiaanb maybe you could comment on this?

Comment (christiaanb) [reply clash-lib/src/Clash/Rewrite/Util.hs:282]: The evaluator is called in multiple places, including `caseCon`. But as @leonschoorl points out, the "introduce free variables" check is quite useful to catch bugs in the Clash compiler, so we want to leave it enabled in as many places as possible. So it's only disabled in `caseCon` as we have a confirmed "false positive" for that transformation.

Comment (martijnbastiaan) [reply clash-lib/src/Clash/Rewrite/Util.hs:282]: Okay, this sounds like: we're aware this is an issue, and we're going to wait until another transformation calling the evaluator is going to blow up..

What we should do is check the other transformations calling the evaluator, check whether they suffer from the same issue, and add a comment explaining why we do (not) need a similar approach as introduced in this PR.
