### PR TITLE
Unroll `unconcat` in more situations than `m=0`

### LINKED ISSUE #1756: *** Exception: Clash.Netlist.BlackBox(201): Couldn't instantiate blackbox
VHDL compilation gives the error:
```
*** Exception: Clash.Netlist.BlackBox(201): Couldn't instantiate blackbox for Clash.Signal.Internal.register#. Verification procedure reported:

Argument 5 should be literal, as blackbox used ~CONST[5], but was:

Identifier (UniqueIdentifier {i_baseName = "a_res", i_baseNameCaseFold = "a_res", i_extensionsRev = [], i_idType = Basic, i_hdl = VHDL, i_provenance = []}) Nothing
```
Verilog compiles just fine.

I  tried to reduce the issue to a simple nonsensical example:
```
topEntity :: Clock  System
          -> Reset  System
          -> Signal System (Vec 1 Bool)
topEntity clk rst = exposeClockResetEnable g clk rst enableGen 

g :: HiddenClockResetEnable dom
  => Signal dom (Vec 1 Bool)
g = out
  where
    a  = register (unconcatI $ singleton (1:: Bit)) a'
    a' = a
    b = pure $ replicate d1 $ replicate d1 True
    (_, out) = unbundle $ f <$> a <*> b

f :: (KnownNat n, KnownNat l, KnownNat m, KnownNat k
  , (m * k) ~ (n * l)) 
  => Vec m (Vec k a1)
  -> Vec m (Vec k a2) 
  -> (Vec m (Vec k a1), Vec l a2)
f a b = (a', out)
  where
    a' = (unconcatI . concat) a
    b' = (unconcatI . concat) b
    out = b'!!0
```
Minor changes to the code fixes the exception, but this example reproduces the error (version 1.4.0).

### PR DESCRIPTION
**Pull request by christiaanb**
Fixes #1756

### CODE REVIEW

File: clash-lib/src/Clash/Normalize/PrimitiveReductions.hs [hunk 1]
```diff
@@ -929,14 +932,41 @@ reduceUnconcat n 0 aTy arg = do
...
+          in  changed retVec
+        else do
+          uniqs0 <- Lens.use uniqSupply
+          let (uniqs1,(vars,elems)) = second (second concat . unzip)
+                                    $ extractElems uniqs0 inScope consCon aTy
+                                       'U' (n*m) arg
+              -- Build a vector out of the first m elements
+              mvec = mkVec nilCon consCon aTy m (take (fromInteger m) vars)
+              -- Get the vector representing the next ((n-1)*m) elements
+              (lbs,head -> nextVec) = splitAt ((2*fromInteger m)-1) elems
```
Comment (martijnbastiaan) [inline clash-lib/src/Clash/Normalize/PrimitiveReductions.hs:951]: I don't understand what's happening here, shouldn't this split at `m`?

File: clash-lib/src/Clash/Normalize/PrimitiveReductions.hs [hunk 2]
```diff
@@ -929,14 +932,41 @@ reduceUnconcat n 0 aTy arg = do
...
-      = let nilVec           = mkVec nilCon consCon aTy 0 []
-            innerVecTy       = mkTyConApp vecTcNm [LitTy (NumTy 0), aTy]
-            retVec           = mkVec nilCon consCon innerVecTy n (replicate (fromInteger n) nilVec)
-        in  changed retVec
+      , let innerVecTy = mkTyConApp vecTcNm [LitTy (NumTy m), aTy]
+      = if n == 0 then
+          changed (mkVecNil nilCon innerVecTy)
+        else if m == 0 then
+          let nilVec           = mkVecNil nilCon aTy
+              retVec           = mkVec nilCon consCon innerVecTy n
```
Comment (martijnbastiaan) [inline clash-lib/src/Clash/Normalize/PrimitiveReductions.hs:940]: Could you remove the weird whitespace?

**Review by martijnbastiaan — CHANGES_REQUESTED** [review]

File: clash-lib/src/Clash/Normalize/PrimitiveReductions.hs (hunk 1 above)
Comment (christiaanb) [reply clash-lib/src/Clash/Normalize/PrimitiveReductions.hs:951]: No, `extractElems` creates 2*N bindings for a vector of `N` long: so for `xs :: Vec 4 a` it creates:
```haskell
x0 = head xs
xs0 = tail xs
x1 = head xs0
xs1 = tail xs0
x2 = head xs1
xs2 = tail xs1
x3 = head xs2
xs3 = tail xs2
```

File: clash-lib/src/Clash/Normalize/PrimitiveReductions.hs [hunk 3]
```diff
@@ -929,14 +932,41 @@ reduceUnconcat n 0 aTy arg = do
...
+                                   (replicate (fromInteger n) nilVec)
+          in  changed retVec
+        else do
+          uniqs0 <- Lens.use uniqSupply
+          let (uniqs1,(vars,elems)) = second (second concat . unzip)
+                                    $ extractElems uniqs0 inScope consCon aTy
```
[the remark this answers is not in the document]
Comment (christiaanb) [reply clash-lib/src/Clash/Normalize/PrimitiveReductions.hs]: Done

File: clash-lib/src/Clash/Normalize/PrimitiveReductions.hs (hunk 2 above)
Comment (christiaanb) [reply clash-lib/src/Clash/Normalize/PrimitiveReductions.hs]: Done

File: clash-lib/src/Clash/Normalize/PrimitiveReductions.hs (hunk 1 above)
Comment (christiaanb) [reply clash-lib/src/Clash/Normalize/PrimitiveReductions.hs]: Improved the comments

**Review by martijnbastiaan — APPROVED** [review]
