### PR TITLE
Use fully qualified names in HDL output dir 

### LINKED ISSUE #1314: Output directory structure doesn't contain full module name
I have a file `MyCircuit/Foo/Top.hs` with the following contents:

```
module MyCircuit.Foo.Top where

import Clash.Prelude
import Clash.Annotations.TH

topEntity
    :: "CLK" ::: Clock System
    -> "INP" ::: Signal System Bit
    -> "OUT" ::: Signal System Bit
topEntity clk = withClock clk $ fmap complement 

makeTopEntity 'topEntity
```

If I synthesize this with

```
clash -outputdir /tmp/foo --verilog MyCircuit.Foo.Top
```

then the resulting files are put in `verilog/MyCircuit/topEntity`, instead of `verilog.MyCircuit.Foo.Top.topEntity`:

```
$ tree /tmp/foo/verilog/
/tmp/foo/verilog/
└── MyCircuit
    └── topEntity
        ├── topEntity.manifest
        └── topEntity.v

2 directories, 2 files
```

This is surprising, and makes code that needs to programmatically access the `.manifest` file, and the generated code, needlessly ad-hoc.

### LINKED ISSUE #1633: How to handle multiple `topEntity` definitions in multiple modules?
Let's say I have two modules, let's call them `A` and `B`, where both define a `topEntity` via `makeTopEntity`, and `B` imports `A` hiding `topEntity`. Normally, if this was `main` instead of `topEntity`, there would be no issue: compiling `A` would make `A.main` into "the" main function, and compiling `B` would make `B.main` (and of course `B.main` is free to use other exported definitions from `A`). But with `topEntity`, this doesn't seem to work.

First try: `clash --verilog B.hs`. This produces weird output showing that first, `B` is compiled into Verilog, then `A` is, overwriting the first compilation's result:

```
$ stack exec -- clash -outputdir _build/tmp --verilog -isrc src/Hardware/SpaceInvaders/SimBoard.hs 
GHC: Parsing and optimising modules took: 9.273s
GHC: Loading external modules from interface files took: 0.020s
GHC: Parsing annotations took: 0.027s
Clash: Parsing and compiling primitives took 0.152s
GHC+Clash: Loading modules cumulatively took 11.526s
Clash: Compiling Hardware.SpaceInvaders.SimBoard.topEntity
Clash: Normalisation took 18.951s
Clash: Netlist generation took 0.449s
Clash: Compiling Hardware.SpaceInvaders.topEntity
Clash: Normalisation took 20.598s
Clash: Netlist generation took 0.657s
Clash: Total compilation took 52.571s
```

(here, `Hardware.SpaceInvaders` stands for `A` and `Hardware.SpaceInvaders.SimBoard` stands for `B`; complete code is at https://github.com/gergoerdi/clash-spaceinvaders/tree/verilator-board but I don't think the details matter)

And if I look at the `topEntity.v` file generated, indeed it contains Verilog generated from `A.topEntity`!

Second try: using `-main-is`. Figuring out the details of how this is supposed to work is tricky.

```
$ stack exec -- clash -outputdir _build/tmp --verilog -isrc src/Hardware/SpaceInvaders/SimBoard.hs -main-is Hardware.SpaceInvaders.SimBoard.topEntity

src/Hardware/SpaceInvaders/SimBoard.hs:1:1: error:
    The IO action ‘main’ is not defined in module ‘Hardware.SpaceInvaders.SimBoard’
  |
1 | module Hardware.SpaceInvaders.SimBoard where
  | ^

```

OK let's try just `topEntity`. This results in an eerie error message:

```$ stack exec -- clash -outputdir _build/tmp --verilog -isrc src/Hardware/SpaceInvaders/SimBoard.hs -main-is topEntity

GHC: Parsing and optimising modules took: 9.204s
GHC: Loading external modules from interface files took: 0.020s
GHC: Parsing annotations took: 0.026s
Clash: Parsing and compiling primitives took 0.148s

<no location info>: error:
    Clash error call:
    Internal error: multiple top entities called topEntity ([Id {varName = Name {nameSort = User, nameOcc = "Hardware.SpaceInvaders.topEntity", nameUniq = 8214565720324087478, nameLoc = RealSrcSpan SrcSpanOneLine "src/Hardware/SpaceInvaders.hs" 36 1 10}, varUniq = 8214565720324087478, varType = AppTy (AppTy (ConstTy Arrow) (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "Clash.Signal.Internal.Clock", nameUniq = 8214565720323789631, nameLoc = UnhelpfulSpan "<no location info>"}))) (LitTy (SymTy "Dom25")))) (AppTy (AppTy (ConstTy Arrow) (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "Clash.Signal.Internal.Reset", nameUniq = 8214565720323789655, nameLoc = UnhelpfulSpan "<no location info>"}))) (LitTy (SymTy "Dom25")))) (AppTy (AppTy (ConstTy Arrow) (AppTy (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "Clash.Signal.Internal.Signal", nameUniq = 8214565720323789676, nameLoc = UnhelpfulSpan "<no location info>"}))) (LitTy (SymTy "Dom25"))) (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "Clash.Sized.Internal.BitVector.BitVector", nameUniq = 8214565720323789708, nameLoc = UnhelpfulSpan "<no location info>"}))) (LitTy (NumTy 8))))) (AppTy (AppTy (ConstTy Arrow) (AppTy (AppTy (AppTy (AppTy (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Tuple.(,,,,)", nameUniq = 3746994889972252682, nameLoc = UnhelpfulSpan "<no location info>"}))) (AppTy (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "Clash.Signal.Internal.Signal", nameUniq = 8214565720323789676, nameLoc = UnhelpfulSpan "<no location info>"}))) (LitTy (SymTy "Dom25"))) (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "RetroClash.Utils.Active", nameUniq = 8214565720323789837, nameLoc = UnhelpfulSpan "<no location info>"}))) (ConstTy (TyCon (Name {nameSort = User, nameOcc = "RetroClash.Utils.High", nameUniq = 8214565720323789842, nameLoc = UnhelpfulSpan "<no location info>"})))))) (AppTy (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "Clash.Signal.Internal.Signal", nameUniq = 8214565720323789676, nameLoc = UnhelpfulSpan "<no location info>"}))) (LitTy (SymTy "Dom25"))) (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "RetroClash.Utils.Active", nameUniq = 8214565720323789837, nameLoc = UnhelpfulSpan "<no location info>"}))) (ConstTy (TyCon (Name {nameSort = User, nameOcc = "RetroClash.Utils.High", nameUniq = 8214565720323789842, nameLoc = UnhelpfulSpan "<no location info>"})))))) (AppTy (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "Clash.Signal.Internal.Signal", nameUniq = 8214565720323789676, nameLoc = UnhelpfulSpan "<no location info>"}))) (LitTy (SymTy "Dom25"))) (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "RetroClash.Utils.Active", nameUniq = 8214565720323789837, nameLoc = UnhelpfulSpan "<no location info>"}))) (ConstTy (TyCon (Name {nameSort = User, nameOcc = "RetroClash.Utils.High", nameUniq = 8214565720323789842, nameLoc = UnhelpfulSpan "<no location info>"})))))) (AppTy (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "Clash.Signal.Internal.Signal", nameUniq = 8214565720323789676, nameLoc = UnhelpfulSpan "<no location info>"}))) (LitTy (SymTy "Dom25"))) (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "RetroClash.Utils.Active", nameUniq = 8214565720323789837, nameLoc = UnhelpfulSpan "<no location info>"}))) (ConstTy (TyCon (Name {nameSort = User, nameOcc = "RetroClash.Utils.High", nameUniq = 8214565720323789842, nameLoc = UnhelpfulSpan "<no location info>"})))))) (AppTy (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "Clash.Signal.Internal.Signal", nameUniq = 8214565720323789676, nameLoc = UnhelpfulSpan "<no location info>"}))) (LitTy (SymTy "Dom25"))) (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "RetroClash.Utils.Active", nameUniq = 8214565720323789837, nameLoc = UnhelpfulSpan "<no location info>"}))) (ConstTy (TyCon (Name {nameSort = User, nameOcc = "RetroClash.Utils.High", nameUniq = 8214565720323789842, nameLoc = UnhelpfulSpan "<no location info>"}))))))) (AppTy (AppTy (ConstTy Arrow) (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "RetroClash.PS2.PS2", nameUniq = 8214565720324080545, nameLoc = UnhelpfulSpan "<no location info>"}))) (LitTy (SymTy "Dom25")))) (AppTy (AppTy (AppTy (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "RetroClash.VGA.VGAOut", nameUniq = 8214565720324058041, nameLoc = UnhelpfulSpan "<no location info>"}))) (LitTy (SymTy "Dom25"))) (LitTy (NumTy 8))) (LitTy (NumTy 8))) (LitTy (NumTy 8))))))), idScope = GlobalId},Id {varName = Name {nameSort = User, nameOcc = "Hardware.SpaceInvaders.SimBoard.topEntity", nameUniq = 8214565720324103336, nameLoc = RealSrcSpan SrcSpanOneLine "src/Hardware/SpaceInvaders/SimBoard.hs" 24 1 10}, varUniq = 8214565720324103336, varType = AppTy (AppTy (ConstTy Arrow) (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "Clash.Signal.Internal.Clock", nameUniq = 8214565720323789631, nameLoc = UnhelpfulSpan "<no location info>"}))) (LitTy (SymTy "System")))) (AppTy (AppTy (ConstTy Arrow) (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "Clash.Signal.Internal.Reset", nameUniq = 8214565720323789655, nameLoc = UnhelpfulSpan "<no location info>"}))) (LitTy (SymTy "System")))) (AppTy (AppTy (ConstTy Arrow) (AppTy (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "Clash.Signal.Internal.Signal", nameUniq = 8214565720323789676, nameLoc = UnhelpfulSpan "<no location info>"}))) (LitTy (SymTy "System"))) (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "Clash.Sized.Internal.BitVector.BitVector", nameUniq = 8214565720323789708, nameLoc = UnhelpfulSpan "<no location info>"}))) (LitTy (NumTy 8))))) (AppTy (AppTy (ConstTy Arrow) (AppTy (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "Clash.Signal.Internal.Signal", nameUniq = 8214565720323789676, nameLoc = UnhelpfulSpan "<no location info>"}))) (LitTy (SymTy "System"))) (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Types.Bool", nameUniq = 3674937295934324744, nameLoc = UnhelpfulSpan "<no location info>"}))))) (AppTy (AppTy (ConstTy Arrow) (AppTy (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "Clash.Signal.Internal.Signal", nameUniq = 8214565720323789676, nameLoc = UnhelpfulSpan "<no location info>"}))) (LitTy (SymTy "System"))) (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Types.Bool", nameUniq = 3674937295934324744, nameLoc = UnhelpfulSpan "<no location info>"}))))) (AppTy (AppTy (ConstTy Arrow) (AppTy (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "Clash.Signal.Internal.Signal", nameUniq = 8214565720323789676, nameLoc = UnhelpfulSpan "<no location info>"}))) (LitTy (SymTy "System"))) (AppTy (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "Hardware.SpaceInvaders.Peripherals.Player", nameUniq = 6989586621679208690, nameLoc = RealSrcSpan SrcSpanMultiLine "src/Hardware/SpaceInvaders/Peripherals.hs" 18 1 22 35}))) (ConstTy (TyCon (Name {nameSort = User, nameOcc = "Barbies.Internal.Wear.Bare", nameUniq = 8214565720323790219, nameLoc = UnhelpfulSpan "<no location info>"})))) (ConstTy (TyCon (Name {nameSort = User, nameOcc = "Data.Functor.Identity.Identity", nameUniq = 8214565720323790010, nameLoc = UnhelpfulSpan "<no location info>"})))))) (AppTy (AppTy (ConstTy Arrow) (AppTy (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "Clash.Signal.Internal.Signal", nameUniq = 8214565720323789676, nameLoc = UnhelpfulSpan "<no location info>"}))) (LitTy (SymTy "System"))) (AppTy (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "Hardware.SpaceInvaders.Peripherals.Player", nameUniq = 6989586621679208690, nameLoc = RealSrcSpan SrcSpanMultiLine "src/Hardware/SpaceInvaders/Peripherals.hs" 18 1 22 35}))) (ConstTy (TyCon (Name {nameSort = User, nameOcc = "Barbies.Internal.Wear.Bare", nameUniq = 8214565720323790219, nameLoc = UnhelpfulSpan "<no location info>"})))) (ConstTy (TyCon (Name {nameSort = User, nameOcc = "Data.Functor.Identity.Identity", nameUniq = 8214565720323790010, nameLoc = UnhelpfulSpan "<no location info>"})))))) (AppTy (AppTy (ConstTy Arrow) (AppTy (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "Clash.Signal.Internal.Signal", nameUniq = 8214565720323789676, nameLoc = UnhelpfulSpan "<no location info>"}))) (LitTy (SymTy "System"))) (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Maybe.Maybe", nameUniq = 3674937295934324792, nameLoc = UnhelpfulSpan "<no location info>"}))) (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "Clash.Sized.Internal.Unsigned.Unsigned", nameUniq = 8214565720323789711, nameLoc = UnhelpfulSpan "<no location info>"}))) (LitTy (NumTy 8)))))) (AppTy (AppTy (ConstTy Arrow) (AppTy (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "Clash.Signal.Internal.Signal", nameUniq = 8214565720323789676, nameLoc = UnhelpfulSpan "<no location info>"}))) (LitTy (SymTy "System"))) (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Maybe.Maybe", nameUniq = 3674937295934324792, nameLoc = UnhelpfulSpan "<no location info>"}))) (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "Clash.Sized.Internal.Index.Index", nameUniq = 8214565720323789709, nameLoc = UnhelpfulSpan "<no location info>"}))) (LitTy (NumTy 224)))))) (AppTy (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Tuple.(,)", nameUniq = 3746994889972252676, nameLoc = UnhelpfulSpan "<no location info>"}))) (AppTy (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "Clash.Signal.Internal.Signal", nameUniq = 8214565720323789676, nameLoc = UnhelpfulSpan "<no location info>"}))) (LitTy (SymTy "System"))) (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Maybe.Maybe", nameUniq = 3674937295934324792, nameLoc = UnhelpfulSpan "<no location info>"}))) (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "Clash.Sized.Internal.Index.Index", nameUniq = 8214565720323789709, nameLoc = UnhelpfulSpan "<no location info>"}))) (AppTy (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.TypeNats.*", nameUniq = 3674937295934325070, nameLoc = UnhelpfulSpan "<no location info>"}))) (AppTy (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.TypeNats.Div", nameUniq = 3674937295934325082, nameLoc = UnhelpfulSpan "<no location info>"}))) (LitTy (NumTy 256))) (LitTy (NumTy 8)))) (LitTy (NumTy 224))))))) (AppTy (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "Clash.Signal.Internal.Signal", nameUniq = 8214565720323789676, nameLoc = UnhelpfulSpan "<no location info>"}))) (LitTy (SymTy "System"))) (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Maybe.Maybe", nameUniq = 3674937295934324792, nameLoc = UnhelpfulSpan "<no location info>"}))) (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "Clash.Sized.Internal.Unsigned.Unsigned", nameUniq = 8214565720323789711, nameLoc = UnhelpfulSpan "<no location info>"}))) (LitTy (NumTy 8)))))))))))))), idScope = GlobalId}]
    ) found in src/Hardware/SpaceInvaders/SimBoard.hs.
    CallStack (from HasCallStack):
      error, called at src-bin-common/Clash/GHCi/Common.hs:63:7 in clash-ghc-1.3.0-J8pqPdvV3DI3lqfzkVaQji:Clash.GHCi.Common
      getMainTopEntity, called at src-bin-881/Clash/GHCi/UI.hs:2155:31 in clash-ghc-1.3.0-J8pqPdvV3DI3lqfzkVaQji:Clash.GHCi.UI
```

Next thing I tried was removing the `makeTopEntity` annotations from both `A` and `B`, and hoping to use `-main-is`:

```
$ stack exec -- clash -outputdir _build/tmp --verilog -isrc src/Hardware/SpaceInvaders/SimBoard.hs -main-is topEntity
GHC: Parsing and optimising modules took: 8.969s
GHC: Loading external modules from interface files took: 0.020s
GHC: Parsing annotations took: 0.026s
Clash: Parsing and compiling primitives took 0.147s
GHC+Clash: Loading modules cumulatively took 11.126s
Clash: Compiling Hardware.SpaceInvaders.SimBoard.topEntity
Clash: Normalisation took 18.746s
Clash: Netlist generation took 0.483s
Clash: Total compilation took 30.582s
```

Looks promising! However, if I look at the resulting `topEntity.v` file, it is not picking up the signal names from the type annotations.

I am out of ideas. Is there any way to make this work, short of refactoring `A` into some `A1` that contains everything but `topEntity`, and importing `A1` into both `A` and `B`?

### PR DESCRIPTION
**Pull request by martijnbastiaan**
To ease integration with external tools, Clash will now create a
separate directory for each top entity under their fully qualified name.
For example, a single module `A` containing two top entities `foo` and
`bar` will produce an HDL folder with two folders in it: `A.foo` and
`A.bar`. Fully qualified names are not influenced by top entity
annotations; instead, the Haskell name of the function is used. Files
within their respective directories will be affected by names set in
annotations.

In order to simplify implementation details, the special status of test
benches has been removed. That means they no longer have a separate code
path in `Clash.Driver` and no longer generate in a subdirectory of a top
entity. This also means that the restriction of one-test-per-topentity
has been relaxed. Top entities can now have an arbitrary number of test
benches, each showing up under their fully qualified name in the
generated HDL.

Even though test benches have no big special status anymore, Clash
still uses their existence as a hint to suppress certain blackbox
warnings. Clash continues to recognize `testBench` as a special
top-level identifier. If no annotation `TestBench` annotation is
attached, it assumes it belongs to `topEntity`.

Because our testsuite was built on many assumptions no longer valid, it
has been restructured to reflect the new situation. VHDL (GHDL) tests
now read manifest files to compile designs. Verilog and SystemVerilog
tests have been restructured in a similar manner. Users of the testsuite
now only have to indicate what entity they'd like to build/run. Other
than that nothing much has changed about the way tests are compiled and
run - making this more a documentation exercise than anything else.

Fixes #1633
Fixes #1314

-------------------

Example output:

```bash
$ stack run clash -- -iexamples/i2c -iexamples/i2c/I2Ctest --verilog -fclash-hdldir i2c_hdl I2Ctest
..
$ tree i2c_hdl
i2c_hdl/
├── I2C.BitMaster.bitMaster
│   ├── bitmaster_bitStateMachine.v
│   ├── bitmaster_busStatusCtrl_0.v
│   ├── bitmaster_busStatusCtrl.v
│   ├── bitmaster.manifest
│   ├── bitmaster.sdc
│   └── bitmaster.v
├── I2C.ByteMaster.byteMaster
│   ├── bytemaster.manifest
│   ├── bytemaster.sdc
│   └── bytemaster.v
├── I2C.i2c
│   ├── i2c.manifest
│   ├── i2c.sdc
│   └── i2c.v
├── I2Ctest.I2CConfig.config
│   ├── configi2c.manifest
│   ├── configi2c.sdc
│   └── configi2c.v
├── I2Ctest.I2CSlave.i2cSlave
│   ├── slave.manifest
│   ├── slave.sdc
│   └── slave.v
└── I2Ctest.system
    ├── system.manifest
    ├── system_system0.v
    └── system.v
```

Example output with test benches:

```$ stack run clash -- -iexamples Calculator --verilog -fclash-hdldir calculator_hdl
..
$ tree calculator_hdl/
calculator_hdl/
├── Calculator.testBench
│   ├── testBench.manifest
│   └── testBench.v
└── Calculator.topEntity
    ├── topEntity.manifest
    ├── topEntity.sdc
    └── topEntity.v

```

-------------------

TODO:
 - [x] Update docs (or rather, look for places that need updating)
 - [x] Add CHANGELOG

### CODE REVIEW

File: clash-ghc/src-ghc/Clash/GHC/LoadModules.hs [hunk 1]
```diff
@@ -729,33 +756,63 @@ findSynthesizeAnnotations bndrs = do
...
+  m (Map.Map CoreSyn.CoreBndr [CoreSyn.CoreBndr])
+findTestBenches bndrs0 = do
+  anns <- findNamedAnnotations bndrs0
+  let
+    duts0 = foldl' insertTb Map.empty (concat (zipWith go0 bndrs0 anns))
+    duts1 = specialCaseMagicName duts0
+  pure duts1
+ where
+  insertTb m (dut, tb) = Map.insertWith (<>) dut [tb] m
+  bndrsMap = HashMap.fromList (zip (map toQualNm bndrs0) bndrs0)
```
Comment (alex-mckenna) [inline clash-ghc/src-ghc/Clash/GHC/LoadModules.hs:778]:
```haskell
(zip (map toQualNm bndrs0) bndrs0)

==>

map (\x -> (toQualNm x, x))
```

File: clash-ghc/src-ghc/Clash/GHC/LoadModules.hs [hunk 2]
```diff
@@ -729,33 +756,63 @@ findSynthesizeAnnotations bndrs = do
...
+  -- tie them to top entities indicated in the annotation.
+  go0 bndr anns = mapMaybe (go1 bndr) anns
+  go1 tbBndr (TestBench dutNm) =
+    case HashMap.lookup (Text.pack (show dutNm)) bndrsMap of
+      Nothing ->
+        Panic.pgmError $
+             "Could not find design under test " <> show (show dutNm) <> ", "
+          <> "associated with test bench " <> show (toQualNm tbBndr) <> ". Note "
+          <> "that testbenches should be exported from the same module as the "
+          <> "design under test."
```
Comment (alex-mckenna) [inline clash-ghc/src-ghc/Clash/GHC/LoadModules.hs:800]: Could you use `[i| ... ]` here?

File: clash-lib/src/Clash/Driver.hs [hunk 3]
```diff
@@ -450,14 +438,14 @@ generateHDL reprs domainConfs bindingsMap hdlState primMap tcm tupTcm typeTrans
       let seen1 = State.execState (mapM_ Id.addRaw (componentNames manifest)) seen0
       return (topTime, manifest, seen1, edamFiles')
     else do
-      -- 1. Normalise topEntity
+      -- 1. Normalize topEntity
```
Comment (alex-mckenna) [inline clash-lib/src/Clash/Driver.hs:441]: :us:

File: clash-lib/src/Clash/Driver.hs [hunk 4]
```diff
@@ -466,86 +454,41 @@ generateHDL reprs domainConfs bindingsMap hdlState primMap tcm tupTcm typeTrans
...
-      let tb' = Data.Text.unpack (nameOcc (varName tb))
-      putStrLn ("Clash: Compiling: " ++ tb')
-      putStrLn ("Clash: Using cached result for: " ++ tb')
-      return topTime
+  Monad.when (opt_edalize opts) $ do
+    let
+      topFiles = fileNames manifest'
+      incFiles = concatMap (\u -> HashMap.lookupDefault [] u edamFiles')
+               $ HashMap.lookupDefault [] (varUniq topEntity) deps
+      edamInfo = createEDAM topNm incFiles topFiles
```
Comment (alex-mckenna) [inline clash-lib/src/Clash/Driver.hs:487]: I would call it `createEdam` instead: no other definition uses EDAM all in capitals right now

Comment (martijnbastiaan) [reply clash-lib/src/Clash/Driver.hs:487]: Ah alright, I didn't really touch that, just changed the indentation. I'll add a separate clean-up commit.

Comment (alex-mckenna) [reply clash-lib/src/Clash/Driver.hs:487]: O snap, that one's my fault then. Whoops...

File: clash-ghc/src-ghc/Clash/GHC/LoadInterfaceFiles.hs [hunk 5]
```diff
@@ -208,29 +208,30 @@ loadExternalExprs'
...
-    (mergeLoadedBinders [loaded0, loaded1, emptyLb{lbClassOps=clsOps''}])
-    (foldl' UniqSet.addListToUniqSet visited0 [collectLbBinders loaded1, clsOps'])
+    (mergeLoadedBinders [loaded0, loaded1, emptyLb{lbClassOps=clsOps1}])
+    (foldl' UniqSet.addListToUniqSet visited0 [collectLbBinders loaded1, map fst clsOps0])
     (es ++ map snd (lbBinders loaded1))
+ where
+  goClsOp :: (Var.Var, GHC.Class) -> (CoreSyn.CoreBndr, Int)
+  goClsOp (v, c) =
+    case elemIndex v (Class.classAllSelIds c) of
+      Nothing -> error ($(curLoc) <> "Internal error: Index not found")
```
Comment (christiaanb) [inline clash-ghc/src-ghc/Clash/GHC/LoadInterfaceFiles.hs:233]: This refactoring would've been a good chance to improve the error message.

File: clash-ghc/src-ghc/Clash/GHC/LoadModules.hs [hunk 6]
```diff
@@ -454,58 +463,77 @@ loadModules useColor hdl modName dflagsM idirs = do
...
+                |]
+              Just top ->
+                -- Note that we return /all/ top entities here, even the ones
+                -- we don't which to synthesize. 'getMainTopEntity' will later
+                -- restrict this to just this top entity (and its dependencies,
+                -- which is why we return everything in the first place).
+                --
+                -- This is quite wasteful though; als Clash will load all
+                -- definitions even though it will end up using just a few. TODO
+                nubSort (top:allImplicit)
```
Comment (christiaanb) [inline clash-ghc/src-ghc/Clash/GHC/LoadModules.hs:510]: Why do we sort them lexicographically?

Comment (martijnbastiaan) [reply clash-ghc/src-ghc/Clash/GHC/LoadModules.hs:510]: The order they come in doesn't really matter as they get topsorted later. This is just to make sure that `top` doesn't appear twice in `top:allImplicit`, which might happen if the binder selected by `-main-is` has a Synthesize annotation. I don't use `nub` as it is `O(n2)`.

File: clash-ghc/src-ghc/Clash/GHC/LoadInterfaceFiles.hs (hunk 5 above)
Comment (martijnbastiaan) [reply clash-ghc/src-ghc/Clash/GHC/LoadInterfaceFiles.hs:233]: I'm not sure what's happening here though, what would be a good error message?

Comment (alex-mckenna) [reply clash-ghc/src-ghc/Clash/GHC/LoadInterfaceFiles.hs:233]: Looks like the error happens when a var isn't in a class. Maybe something like _could not find a binder for <var> in <class>_ if you can get nice names for each

Comment (christiaanb) [reply clash-ghc/src-ghc/Clash/GHC/LoadInterfaceFiles.hs:233]: Yeah, if we error out it means that we couldn't find a class-method called `v` in the class `c`.

File: clash-lib/src/Clash/Driver.hs (hunk 4 above)
Comment (martijnbastiaan) [reply clash-lib/src/Clash/Driver.hs:487]: I'm going to refactor this in another PR if you don't mind.
