### PR TITLE
Print previous errors if local module fails to load

### LINKED ISSUE #2365: Non-sensical error message when failing to parse InlineYaml from precompiled module
If your (starter) project contains a primitive such as:

```
...
{-# NOINLINE foo #-}
{-# ANN foo hasBlackBox #-}
{-# ANN foo (InlineYamlPrimitive [minBound..] [__i|
 BlackBox:
   kind: Declaration
   name: Some.Incorrect.Name.bar
   template: |-
     // begin foo
     foo
     // end foo
|]) #-}
```

Clash will fail with a very misleading error message:

```
<no location info>: error:
    module ‘Some.Correct.Name’ cannot be found locally
```

Ultimately, this is caused by functions in `LoadInterfaceFiles` not propagating up their errors cleanly:

https://github.com/clash-lang/clash-compiler/blob/a8b213ab86df143c9e259dd58ced8ec81f4eee5b/clash-ghc/src-ghc/Clash/GHC/LoadInterfaceFiles.hs#L405-L461

The error Clash should have given is:

> Function `Some.Correct.Name.foo` was annotated with an inline primitive for `Some.Incorrect.Name.bar`. These names should be the same.

### PR DESCRIPTION
**Pull request by martijnbastiaan**
Fixes #2365

---------------------------

Example of a new-style error message:

```
<no location info>: error:
    Other error:
    Failed to load module 'Bittide.Instances.Hitl.Tcl.ExtraProbes'.
    
    Tried to load it from precompiled sources, error was:
    
      Function Clash.Cores.Xilinx.Dna.dnaPorte2 was annotated with an inline primitive for Clash.Cores.Xilinx.DnaPorte.deviceDna.dnaPorte2. These names should be the same.
      CallStack (from HasCallStack):
        error, called at src-ghc/Clash/GHC/LoadInterfaceFiles.hs:482:5 in clash-ghc-1.9.0-inplace:Clash.GHC.LoadInterfaceFiles
    
    Tried to load it from local sources, error was:
    
      module ‘Bittide.Instances.Hitl.Tcl.ExtraProbes’ cannot be found locally
```

Instead of the old:

```
<no location info>: error:
    Other error: 
      module ‘Bittide.Instances.Hitl.Tcl.ExtraProbes’ cannot be found locally
```

## Still TODO:

  - [X] Write a changelog entry (see changelog/README.md)
  - [X] Check copyright notices are up to date in edited files

### CODE REVIEW

File: clash-ghc/src-ghc/Clash/GHC/LoadModules.hs [hunk 1]
```diff
@@ -11,6 +11,7 @@
 {-# LANGUAGE FlexibleContexts #-}
 {-# LANGUAGE LambdaCase #-}
 {-# LANGUAGE NamedFieldPuns #-}
+{-# LANGUAGE DeriveAnyClass #-}
 {-# LANGUAGE QuasiQuotes #-}
 {-# LANGUAGE RecordWildCards #-}
 {-# LANGUAGE TemplateHaskell #-}
```
Comment (lmbollen) [inline clash-ghc/src-ghc/Clash/GHC/LoadModules.hs:17]: sort

File: clash-lib/src/Clash/Driver.hs [hunk 2]
```diff
@@ -720,36 +725,42 @@ compilePrimitive idirs pkgDbs topDir
...
 
 compilePrimitive _ _ _ (Primitive pNm wf typ) =
   return (Primitive pNm wf typ)
 {-# SCC compilePrimitive #-}
 
-processHintError
-  :: Monad m
-  => String
-  -> Data.Text.Text
-  -> (t -> r)
```
Comment (martijnbastiaan) [inline clash-lib/src/Clash/Driver.hs:734]: Note for reviewers: there's a slight refactor in here. I've removed the `(t -> r)` argument. Is now handled by the caller.

**Review by lmbollen — APPROVED** [review]
LGTM modulo simple comment

**Review by christiaanb — APPROVED** [review]
LGTM

File: clash-ghc/src-ghc/Clash/GHC/LoadModules.hs [hunk 3]
```diff
@@ -570,7 +592,15 @@ loadModules startAction useColor hdl modName dflagsM idirs = do
       -- We need to try and load external modules first, because we can't
       -- recover from errors in 'loadLocalModule'.
       loadExternalModule hdl modName >>= \case
-        Left _loadExternalErr -> loadLocalModule hdl modName
+        Left loadExternalErr -> do
+          liftIO $ print loadExternalErr
```
Comment (martijnbastiaan) [inline clash-ghc/src-ghc/Clash/GHC/LoadModules.hs:596]: Woops
