### PR TITLE
Make `ensureSpine` on Clash number types synthesizable

### LINKED ISSUE #3021: Synthesis fails for `ensureSpine` on Clash number types
Doing `clash --vhdl T3021.hs` on:
``` haskell
module T3021 where

import Clash.Prelude

topEntity :: Unsigned 8 -> Unsigned 8
topEntity = ensureSpine
```
results in:
```
<no location info>: error:
    Clash error call:
    Clash.Netlist(1121): mkDcApplication undefined for: (Unsigned 8,Name {nameSort = User, nameOcc = "Clash.Sized.Internal.Unsigned.U", nameUniq = 8214565720323800539, nameLoc = UnhelpfulSpan UnhelpfulNoLocationInfo},[Tick (NameMod PrefixName (LitTy (SymTy "$fNFDataXUnsigned_f"))) (Tick (NameMod PrefixName (LitTy (SymTy "ensureSpine"))) (Tick (NameMod PrefixName (LitTy (SymTy "$fNFDataXNatural"))) (Tick (NameMod PrefixName (LitTy (SymTy "id"))) (Tick (NameMod PrefixName (LitTy (SymTy "$fGenericUnsigned_$cfrom"))) (Case (Var (Id {varName = Name {nameSort = Internal, nameOcc = "carg", nameUniq = 0, nameLoc = UnhelpfulSpan UnhelpfulNoLocationInfo}, varUniq = 0, varType = AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "Clash.Sized.Internal.Unsigned.Unsigned", nameUniq = 8214565720323790023, nameLoc = RealSrcSpan SrcSpanOneLine "T3021.hs" 6 1 10 (Just (BufSpan {bufSpanStart = BufPos {bufPos = 80}, bufSpanEnd = BufPos {bufPos = 89}}))}))) (LitTy (NumTy 8)), idScope = LocalId})) (AppTy (AppTy (AppTy (AppTy (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Internal.Generics.M1", nameUniq = 3674937295934325016, nameLoc = UnhelpfulSpan UnhelpfulNoLocationInfo}))) (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Prim.TYPE", nameUniq = 3674937295934324918, nameLoc = UnhelpfulSpan UnhelpfulNoLocationInfo}))) (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Types.BoxedRep", nameUniq = 3891110078048108766, nameLoc = UnhelpfulSpan UnhelpfulNoLocationInfo}))) (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Types.Lifted", nameUniq = 3891110078048108808, nameLoc = UnhelpfulSpan UnhelpfulNoLocationInfo})))))) (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Internal.Generics.C", nameUniq = 3674937295934325030, nameLoc = UnhelpfulSpan UnhelpfulNoLocationInfo})))) (AppTy (AppTy (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Internal.Generics.MetaCons", nameUniq = 3891110078048108751, nameLoc = UnhelpfulSpan UnhelpfulNoLocationInfo}))) (LitTy (SymTy "U"))) (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Internal.Generics.PrefixI", nameUniq = 3891110078048108706, nameLoc = UnhelpfulSpan UnhelpfulNoLocationInfo})))) (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Types.True", nameUniq = 3891110078048108586, nameLoc = UnhelpfulSpan UnhelpfulNoLocationInfo}))))) (AppTy (AppTy (AppTy (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Internal.Generics.M1", nameUniq = 3674937295934325016, nameLoc = UnhelpfulSpan UnhelpfulNoLocationInfo}))) (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Prim.TYPE", nameUniq = 3674937295934324918, nameLoc = UnhelpfulSpan UnhelpfulNoLocationInfo}))) (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Types.BoxedRep", nameUniq = 3891110078048108766, nameLoc = UnhelpfulSpan UnhelpfulNoLocationInfo}))) (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Types.Lifted", nameUniq = 3891110078048108808, nameLoc = UnhelpfulSpan UnhelpfulNoLocationInfo})))))) (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Internal.Generics.S", nameUniq = 3674937295934325032, nameLoc = UnhelpfulSpan UnhelpfulNoLocationInfo})))) (AppTy (AppTy (AppTy (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Internal.Generics.MetaSel", nameUniq = 3891110078048108754, nameLoc = UnhelpfulSpan UnhelpfulNoLocationInfo}))) (AppTy (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Internal.Maybe.Just", nameUniq = 3891110078048108568, nameLoc = UnhelpfulSpan UnhelpfulNoLocationInfo}))) (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Types.Symbol", nameUniq = 3674937295934325536, nameLoc = UnhelpfulSpan UnhelpfulNoLocationInfo})))) (LitTy (SymTy "unsafeToNatural")))) (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Internal.Generics.NoSourceUnpackedness", nameUniq = 3891110078048108727, nameLoc = UnhelpfulSpan UnhelpfulNoLocationInfo})))) (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Internal.Generics.SourceStrict", nameUniq = 3891110078048108733, nameLoc = UnhelpfulSpan UnhelpfulNoLocationInfo})))) (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Internal.Generics.DecidedStrict", nameUniq = 3891110078048108742, nameLoc = UnhelpfulSpan UnhelpfulNoLocationInfo}))))) (AppTy (AppTy (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Internal.Generics.K1", nameUniq = 3674937295934325014, nameLoc = UnhelpfulSpan UnhelpfulNoLocationInfo}))) (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Prim.TYPE", nameUniq = 3674937295934324918, nameLoc = UnhelpfulSpan UnhelpfulNoLocationInfo}))) (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Types.BoxedRep", nameUniq = 3891110078048108766, nameLoc = UnhelpfulSpan UnhelpfulNoLocationInfo}))) (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Types.Lifted", nameUniq = 3891110078048108808, nameLoc = UnhelpfulSpan UnhelpfulNoLocationInfo})))))) (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Internal.Generics.R", nameUniq = 3674937295934325024, nameLoc = UnhelpfulSpan UnhelpfulNoLocationInfo})))) (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Num.Natural.Natural", nameUniq = 3674937295934324786, nameLoc = UnhelpfulSpan UnhelpfulNoLocationInfo})))))) (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Types.Any", nameUniq = 3674937295934325108, nameLoc = UnhelpfulSpan UnhelpfulNoLocationInfo}))) (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Prim.TYPE", nameUniq = 3674937295934324918, nameLoc = UnhelpfulSpan UnhelpfulNoLocationInfo}))) (AppTy (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Types.BoxedRep", nameUniq = 3891110078048108766, nameLoc = UnhelpfulSpan UnhelpfulNoLocationInfo}))) (ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Types.Lifted", nameUniq = 3891110078048108808, nameLoc = UnhelpfulSpan UnhelpfulNoLocationInfo}))))))) [(DataPat Name {nameSort = User, nameOcc = "Clash.Sized.Internal.Unsigned.U", nameUniq = 8214565720323800539, nameLoc = UnhelpfulSpan UnhelpfulNoLocationInfo} [] [Id {varName = Name {nameSort = User, nameOcc = "g1", nameUniq = 8214565720323807230, nameLoc = UnhelpfulSpan UnhelpfulNoLocationInfo}, varUniq = 8214565720323807230, varType = ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Num.Natural.Natural", nameUniq = 3674937295934324786, nameLoc = UnhelpfulSpan UnhelpfulNoLocationInfo})), idScope = LocalId}],Var (Id {varName = Name {nameSort = User, nameOcc = "g1", nameUniq = 8214565720323807230, nameLoc = UnhelpfulSpan UnhelpfulNoLocationInfo}, varUniq = 8214565720323807230, varType = ConstTy (TyCon (Name {nameSort = User, nameOcc = "GHC.Num.Natural.Natural", nameUniq = 3674937295934324786, nameLoc = UnhelpfulSpan UnhelpfulNoLocationInfo})), idScope = LocalId}))])))))],[Just (Unsigned 64)])
    CallStack (from HasCallStack):
      error, called at src/Clash/Netlist.hs:1121:9 in clash-lib-1.9.0-inplace:Clash.Netlist
      mkDcApplication, called at src/Clash/Netlist.hs:835:16 in clash-lib-1.9.0-inplace:Clash.Netlist
      mkExpr, called at src/Clash/Netlist.hs:444:30 in clash-lib-1.9.0-inplace:Clash.Netlist
      mkDeclarations', called at src/Clash/Netlist.hs:403:18 in clash-lib-1.9.0-inplace:Clash.Netlist
      mkDeclarations, called at src/Clash/Netlist.hs:278:40 in clash-lib-1.9.0-inplace:Clash.Netlist
      genComponentT, called at src/Clash/Netlist.hs:241:41 in clash-lib-1.9.0-inplace:Clash.Netlist
      genComponent, called at src/Clash/Netlist.hs:119:9 in clash-lib-1.9.0-inplace:Clash.Netlist
```

### PR DESCRIPTION
**Pull request by christiaanb**
Fixes #3021

### CODE REVIEW

File: clash-prelude/src/Clash/Sized/Internal/BitVector.hs [hunk 1]
```diff
@@ -298,6 +298,7 @@ instance ShowX Bit where
 
 instance NFDataX Bit where
   deepErrorX = errorX
+  ensureSpine = id
```
Comment (martijnbastiaan) [inline clash-prelude/src/Clash/Sized/Internal/BitVector.hs]: As discussed in the office, this should behave like BitVector
