### PR TITLE
Substitute inlined vars in resulting letrecs too in  `inlineBndrsCleanup`

### LINKED ISSUE #1337: `inlineCleanup` introduces free variables
**Updated issue report 19 May 2020:**

If `inlineCleanup` is given an expression of the following form:

```
let
  result = a

  a = b
  b = c
  c = a b
in
  result
```

Depending on the actual expressions that the various binders represent, it will determine `result` is a binding that should be "kept", while all others should be inlined. `inlineBndrsCleanup` will try to do this, but it currently fails to handle this case correctly. It will yield:

```haskell
let
  result = b
  b = a b
in 
  result
```

i.e., it will introduce a free variable!

------------------------------

**Original issue report 18 May 2020:**

Compiling the following:

```haskell
{-# LANGUAGE GADTs               #-}
{-# LANGUAGE NoImplicitPrelude   #-}
{-# LANGUAGE RecordWildCards     #-}

module Test where

import Clash.Prelude

type Lanes = 2

data SigFn a b = SigFn { runSigFn :: SigType a -> SigType b }

class Sig a where
  type SigType a

instance Sig Bit where
  type SigType Bit = Signal System Bit

instance Sig a => Sig (Vec n a) where
  type SigType (Vec n a) = Vec n (SigType a)

instance (Sig a, Sig b) => Sig (a, b) where
  type SigType (a, b) = (SigType a, SigType b)

singletonSigFn :: SigFn a (Vec 1 a)
singletonSigFn = SigFn singleton

headSigFn :: SigFn (Vec 1 a) a
headSigFn = SigFn head

defSigFn :: Default (SigType t) => SigFn s t
defSigFn = SigFn (const def)

(>>>) :: SigFn a b -> SigFn b c -> SigFn a c
SigFn f >>> SigFn g = SigFn (g . f)

(<=>) :: SigFn a b -> SigFn c d -> SigFn (a, c) (b, d)
SigFn f <=> SigFn g = SigFn (\(x, y) -> (f x, g y))

splitSigFn :: KnownNat n => SigFn (Vec (n + m) a) (Vec n a, Vec m a)
splitSigFn = SigFn splitAtI

catSigFn :: SigFn (Vec n a, Vec m a) (Vec (n + m) a)
catSigFn = SigFn (\(x, y) -> x ++ y)

data BitLayout t where
  BitLayout :: forall bitCount t
            .  ( KnownNat bitCount )
            => { bitCount :: SNat bitCount
               , inFn :: SigFn t (Vec bitCount Bit)
               , outFn :: SigFn (Vec bitCount Bit) t
               }
            -> BitLayout t

unitLayout :: BitLayout Bit
unitLayout = BitLayout SNat singletonSigFn headSigFn

voidLayout :: forall t . Default (SigType t) => BitLayout t
voidLayout = BitLayout d0 defSigFn defSigFn

catLayout
  :: forall n m s
  .  ( KnownNat n
     , KnownNat m
     , 1 <= n )
  => BitLayout (Vec n s)
  -> BitLayout (Vec m s)
  -> BitLayout (Vec (n + m) s)
catLayout (BitLayout aBitCount aInFn aOutFn) (BitLayout bBitCount bInFn bOutFn) = let
  inFn = splitSigFn >>> (aInFn <=> bInFn) >>> catSigFn
  outFn = splitSigFn >>> (aOutFn <=> bOutFn) >>> catSigFn
  in BitLayout SNat inFn outFn

vecLayout
  :: forall n n' t
  .  ( n' ~ (n - 1)
     , 1 <= n
     , KnownNat n
     , KnownNat n' )
  => Vec n (BitLayout t)
  -> BitLayout (Vec n t)
vecLayout (BitLayout{..} :> others) = let
  headLayout = BitLayout SNat (headSigFn >>> inFn) (outFn >>> singletonSigFn)
  in case others of
       Nil -> headLayout
       _ -> headLayout `catLayout` vecLayout @n' others

layout :: BitLayout (Vec Lanes Bit)
layout = mkPos (0 :: Index (Lanes + 1))

mkPos
  :: forall rp
  .  ( KnownNat rp
     , 1 <= rp
     )
  => Index (rp + 1)
  -> BitLayout (Vec rp Bit)
mkPos n = let
  lanes = map (\i -> if i < n
                     then unitLayout
                     else voidLayout) $ iterateI succ 0
  in vecLayout lanes

runBitLayout
  :: Default (SigType t)
  => BitLayout t
  -> SigType t
  -> SigType t
runBitLayout BitLayout{..} = runSigFn ( inFn >>> outFn )

topEntity :: Vec Lanes (Signal System Bit) -> Vec Lanes (Signal System Bit)
topEntity = runBitLayout layout
```

with 

```cabal new-run clash -- Test.hs --vhdl -fclash-debug DebugSilent -fclash-compile-ultra```

yields:

```
<no location info>: error:
    Clash error call:
    Clash.Rewrite.Util(232): Error when applying rewrite inlineCleanup to:
    letrec
      result[31996] :: Test.SigType[8214565720323817080]
                         (Clash.Sized.Vector.Vec[8214565720323788085]
                            2
                            Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
      = case c$case_scrut[31995][LocalId] of
          GHC.Types.False[3891110078048108556]  ->
            result[31849][LocalId]
          GHC.Types.True[3891110078048108589]  ->
            result[31994][LocalId]
      c$case_scrut[31995] :: GHC.Types.Bool[3674937295934324744]
      = Clash.Sized.Internal.Index.lt#
          @(GHC.TypeNats.+[3674937295934325068] 2 1)
          elH0[279][LocalId]
          (Clash.Sized.Internal.Index.fromInteger# @3 3 0)
      result[31994] :: Test.SigType[8214565720323817080]
                         (Clash.Sized.Vector.Vec[8214565720323788085]
                            2
                            Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
      = case c$case_scrut[31848][LocalId] of
          GHC.Types.False[3891110078048108556]  ->
            result[31918][LocalId]
          GHC.Types.True[3891110078048108589]  ->
            result[31985][LocalId]
      result[31985] :: Clash.Sized.Vector.Vec[8214565720323788085]
                         2
                         (Test.SigType[8214565720323817080]
                            Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
      = Clash.Sized.Vector.Cons[8214565720323788088]
          @2
          @(Test.SigType[8214565720323817080]
              Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
          @1
          _CO_
          <prefixName>"unitLayout"
          <prefixName>"headSigFn"
          elH0[11213][LocalId]
          c$app_arg[31984][LocalId]
      c$app_arg[31984] :: Clash.Sized.Vector.Vec[8214565720323788085]
                            1
                            (Test.SigType[8214565720323817080]
                               Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
      = Clash.Sized.Vector.Cons[8214565720323788088]
          @1
          @(Test.SigType[8214565720323817080]
              Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
          @0
          _CO_
          <prefixName>"unitLayout"
          <prefixName>"headSigFn"
          elH0[15333][LocalId]
          (Clash.Sized.Vector.Nil[8214565720323788089] @0
             @(Test.SigType[8214565720323817080]
                 Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
             _CO_)
      result[31918] :: Clash.Sized.Vector.Vec[8214565720323788085]
                         2
                         (Test.SigType[8214565720323817080]
                            Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
      = Clash.Sized.Vector.Cons[8214565720323788088]
          @2
          @(Test.SigType[8214565720323817080]
              Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
          @1
          _CO_
          <prefixName>"unitLayout"
          <prefixName>"headSigFn"
          elH0[11013][LocalId]
          (Clash.Sized.Vector.Cons[8214565720323788088] @1
             @(Test.SigType[8214565720323817080]
                 Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
             @0
             _CO_
             <prefixName>"layout_$svoidLayout"
             <prefixName>"layout1"
             <prefixName>"layout2"
             <prefixName>"layout3"
             Clash.Sized.Internal.BitVector.low
             (Clash.Sized.Vector.Nil[8214565720323788089] @0
                @(Test.SigType[8214565720323817080]
                    Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
                _CO_))
      result[31849] :: Test.SigType[8214565720323817080]
                         (Clash.Sized.Vector.Vec[8214565720323788085]
                            2
                            Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
      = case c$case_scrut[31848][LocalId] of
          GHC.Types.False[3891110078048108556]  ->
            Clash.Sized.Vector.Cons[8214565720323788088] @2
              @(Test.SigType[8214565720323817080]
                  Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
              @1
              _CO_
              <prefixName>"layout_$svoidLayout"
              <prefixName>"layout1"
              <prefixName>"layout2"
              <prefixName>"layout3"
              Clash.Sized.Internal.BitVector.low
              (Clash.Sized.Vector.Cons[8214565720323788088] @1
                 @(Test.SigType[8214565720323817080]
                     Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
                 @0
                 _CO_
                 <prefixName>"layout_$svoidLayout"
                 <prefixName>"layout1"
                 <prefixName>"layout2"
                 <prefixName>"layout3"
                 Clash.Sized.Internal.BitVector.low
                 (Clash.Sized.Vector.Nil[8214565720323788089] @0
                    @(Test.SigType[8214565720323817080]
                        Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
                    _CO_))
          GHC.Types.True[3891110078048108589]  ->
            c$case_alt[31847][LocalId]
      c$case_scrut[31848] :: GHC.Types.Bool[3674937295934324744]
      = Clash.Sized.Internal.Index.lt#
          @(GHC.TypeNats.+[3674937295934325068] 2 1)
          elA1[439][LocalId]
          (Clash.Sized.Internal.Index.fromInteger# @3 3 0)
      c$case_alt[31847] :: Clash.Sized.Vector.Vec[8214565720323788085]
                             2
                             (Test.SigType[8214565720323817080]
                                Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
      = Clash.Sized.Vector.Cons[8214565720323788088]
          @2
          @(Test.SigType[8214565720323817080]
              Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
          @1
          _CO_
          <prefixName>"layout_$svoidLayout"
          <prefixName>"layout1"
          <prefixName>"layout2"
          <prefixName>"layout3"
          Clash.Sized.Internal.BitVector.low
          c$app_arg[31839][LocalId]
      c$app_arg[31839] :: Clash.Sized.Vector.Vec[8214565720323788085]
                            1
                            (Test.SigType[8214565720323817080]
                               Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
      = Clash.Sized.Vector.Cons[8214565720323788088]
          @1
          @(Test.SigType[8214565720323817080]
              Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
          @0
          _CO_
          <prefixName>"unitLayout"
          <prefixName>"headSigFn"
          elH0[14309][LocalId]
          (Clash.Sized.Vector.Nil[8214565720323788089] @0
             @(Test.SigType[8214565720323817080]
                 Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
             _CO_)
      elH0[15333] :: Test.SigType[8214565720323817080]
                       Clash.Sized.Internal.BitVector.Bit[8214565720323788076]
      = case y[6989586621679044938][LocalId] of
          Clash.Sized.Vector.Cons[8214565720323788088] m[15328]
            (_co_[15331] :: GHC.Prim.~#[3674937295934324842]
                              GHC.Types.Nat[3674937295934325064]
                              GHC.Types.Nat[3674937295934325064]
                              1
                              (GHC.TypeNats.+[3674937295934325068] 0 1))
              (el[15330] :: Test.SigType[8214565720323817080]
                              Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
              (rest[15329] :: Clash.Sized.Vector.Vec[8214565720323788085]
                                0
                                (Test.SigType[8214565720323817080]
                                   Clash.Sized.Internal.BitVector.Bit[8214565720323788076])) ->
            el[15330][LocalId]
      y[6989586621679044938] :: Test.SigType[8214565720323817080]
                                  (Clash.Sized.Vector.Vec[8214565720323788085]
                                     1
                                     Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
      = case c$case_scrut[31986][LocalId] of
          GHC.Tuple.(,)[3963167672086036486]
            (c$wild[31990] :: Clash.Sized.Vector.Vec[8214565720323788085]
                                1
                                (Test.SigType[8214565720323817080]
                                   Clash.Sized.Internal.BitVector.Bit[8214565720323788076]))
              (c$sel[31992] :: Clash.Sized.Vector.Vec[8214565720323788085]
                                 1
                                 (Test.SigType[8214565720323817080]
                                    Clash.Sized.Internal.BitVector.Bit[8214565720323788076])) ->
            c$sel[31992][LocalId]
      elH0[14309] :: Test.SigType[8214565720323817080]
                       Clash.Sized.Internal.BitVector.Bit[8214565720323788076]
      = case y[6989586621679044887][LocalId] of
          Clash.Sized.Vector.Cons[8214565720323788088] m[14304]
            (_co_[14307] :: GHC.Prim.~#[3674937295934324842]
                              GHC.Types.Nat[3674937295934325064]
                              GHC.Types.Nat[3674937295934325064]
                              1
                              (GHC.TypeNats.+[3674937295934325068] 0 1))
              (el[14306] :: Test.SigType[8214565720323817080]
                              Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
              (rest[14305] :: Clash.Sized.Vector.Vec[8214565720323788085]
                                0
                                (Test.SigType[8214565720323817080]
                                   Clash.Sized.Internal.BitVector.Bit[8214565720323788076])) ->
            el[14306][LocalId]
      y[6989586621679044887] :: Test.SigType[8214565720323817080]
                                  (Clash.Sized.Vector.Vec[8214565720323788085]
                                     1
                                     Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
      = case c$case_scrut[31840][LocalId] of
          GHC.Tuple.(,)[3963167672086036486]
            (c$wild[31844] :: Clash.Sized.Vector.Vec[8214565720323788085]
                                0
                                (Test.SigType[8214565720323817080]
                                   Clash.Sized.Internal.BitVector.Bit[8214565720323788076]))
              (c$sel[31846] :: Clash.Sized.Vector.Vec[8214565720323788085]
                                 1
                                 (Test.SigType[8214565720323817080]
                                    Clash.Sized.Internal.BitVector.Bit[8214565720323788076])) ->
            c$sel[31846][LocalId]
      c$case_scrut[31840] :: GHC.Tuple.(,)[3746994889972252676]
                               (Clash.Sized.Vector.Vec[8214565720323788085]
                                  0
                                  (Test.SigType[8214565720323817080]
                                     Clash.Sized.Internal.BitVector.Bit[8214565720323788076]))
                               (Clash.Sized.Vector.Vec[8214565720323788085]
                                  1
                                  (Test.SigType[8214565720323817080]
                                     Clash.Sized.Internal.BitVector.Bit[8214565720323788076]))
      = Clash.Sized.Vector.splitAt @0 @1
          @(Test.SigType[8214565720323817080]
              Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
          (Clash.Promoted.Nat.SNat[8214565720323787967] @0
             <prefixName>"layout_$svoidLayout"
             <prefixName>"$s$WBitLayout1"
             0)
          c$app_arg[31950][LocalId]
      elH0[11213] :: Test.SigType[8214565720323817080]
                       Clash.Sized.Internal.BitVector.Bit[8214565720323788076]
      = case x[6989586621679044936][LocalId] of
          Clash.Sized.Vector.Cons[8214565720323788088] m[11208]
            (_co_[11211] :: GHC.Prim.~#[3674937295934324842]
                              GHC.Types.Nat[3674937295934325064]
                              GHC.Types.Nat[3674937295934325064]
                              1
                              (GHC.TypeNats.+[3674937295934325068] 0 1))
              (el[11210] :: Test.SigType[8214565720323817080]
                              Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
              (rest[11209] :: Clash.Sized.Vector.Vec[8214565720323788085]
                                0
                                (Test.SigType[8214565720323817080]
                                   Clash.Sized.Internal.BitVector.Bit[8214565720323788076])) ->
            el[11210][LocalId]
      x[6989586621679044936] :: Test.SigType[8214565720323817080]
                                  (Clash.Sized.Vector.Vec[8214565720323788085]
                                     1
                                     Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
      = case c$case_scrut[31986][LocalId] of
          GHC.Tuple.(,)[3963167672086036486]
            (c$sel[31989] :: Clash.Sized.Vector.Vec[8214565720323788085]
                               1
                               (Test.SigType[8214565720323817080]
                                  Clash.Sized.Internal.BitVector.Bit[8214565720323788076]))
              (c$wild[31988] :: Clash.Sized.Vector.Vec[8214565720323788085]
                                  1
                                  (Test.SigType[8214565720323817080]
                                     Clash.Sized.Internal.BitVector.Bit[8214565720323788076])) ->
            c$sel[31989][LocalId]
      c$case_scrut[31986] :: GHC.Tuple.(,)[3746994889972252676]
                               (Clash.Sized.Vector.Vec[8214565720323788085]
                                  1
                                  (Test.SigType[8214565720323817080]
                                     Clash.Sized.Internal.BitVector.Bit[8214565720323788076]))
                               (Clash.Sized.Vector.Vec[8214565720323788085]
                                  1
                                  (Test.SigType[8214565720323817080]
                                     Clash.Sized.Internal.BitVector.Bit[8214565720323788076]))
      = Clash.Sized.Vector.splitAt @1 @1
          @(Test.SigType[8214565720323817080]
              Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
          (Clash.Promoted.Nat.SNat[8214565720323787967] @1
             <prefixName>"unitLayout"
             <prefixName>"$s$WBitLayout3"
             1)
          result[31951][LocalId]
      result[31951] :: Clash.Sized.Vector.Vec[8214565720323788085]
                         2
                         (Test.SigType[8214565720323817080]
                            Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
      = Clash.Sized.Vector.Cons[8214565720323788088]
          @2
          @(Test.SigType[8214565720323817080]
              Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
          @1
          _CO_
          <prefixName>"unitLayout"
          <prefixName>"singletonSigFn"
          <prefixName>"singletonSigFn1"
          elH0[5893][LocalId]
          c$app_arg[31950][LocalId]
      c$app_arg[31950] :: Clash.Sized.Vector.Vec[8214565720323788085]
                            1
                            (Test.SigType[8214565720323817080]
                               Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
      = <prefixName>"unitLayout"
      <prefixName>"singletonSigFn"
      <prefixName>"singletonSigFn1"
      Clash.Sized.Vector.Cons[8214565720323788088] @1
        @(Test.SigType[8214565720323817080]
            Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
        @0
        _CO_
        elH0[4875][LocalId]
        (Clash.Sized.Vector.Nil[8214565720323788089] @0
           @(Test.SigType[8214565720323817080]
               Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
           _CO_)
      elH0[11013] :: Test.SigType[8214565720323817080]
                       Clash.Sized.Internal.BitVector.Bit[8214565720323788076]
      = case x[6989586621679044914][LocalId] of
          Clash.Sized.Vector.Cons[8214565720323788088] m[11008]
            (_co_[11011] :: GHC.Prim.~#[3674937295934324842]
                              GHC.Types.Nat[3674937295934325064]
                              GHC.Types.Nat[3674937295934325064]
                              1
                              (GHC.TypeNats.+[3674937295934325068] 0 1))
              (el[11010] :: Test.SigType[8214565720323817080]
                              Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
              (rest[11009] :: Clash.Sized.Vector.Vec[8214565720323788085]
                                0
                                (Test.SigType[8214565720323817080]
                                   Clash.Sized.Internal.BitVector.Bit[8214565720323788076])) ->
            el[11010][LocalId]
      x[6989586621679044914] :: Test.SigType[8214565720323817080]
                                  (Clash.Sized.Vector.Vec[8214565720323788085]
                                     1
                                     Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
      = case c$case_scrut[31919][LocalId] of
          GHC.Tuple.(,)[3963167672086036486]
            (c$sel[31922] :: Clash.Sized.Vector.Vec[8214565720323788085]
                               1
                               (Test.SigType[8214565720323817080]
                                  Clash.Sized.Internal.BitVector.Bit[8214565720323788076]))
              (c$wild[31921] :: Clash.Sized.Vector.Vec[8214565720323788085]
                                  0
                                  (Test.SigType[8214565720323817080]
                                     Clash.Sized.Internal.BitVector.Bit[8214565720323788076])) ->
            c$sel[31922][LocalId]
      c$case_scrut[31919] :: GHC.Tuple.(,)[3746994889972252676]
                               (Clash.Sized.Vector.Vec[8214565720323788085]
                                  1
                                  (Test.SigType[8214565720323817080]
                                     Clash.Sized.Internal.BitVector.Bit[8214565720323788076]))
                               (Clash.Sized.Vector.Vec[8214565720323788085]
                                  0
                                  (Test.SigType[8214565720323817080]
                                     Clash.Sized.Internal.BitVector.Bit[8214565720323788076]))
      = Clash.Sized.Vector.splitAt @1 @0
          @(Test.SigType[8214565720323817080]
              Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
          (Clash.Promoted.Nat.SNat[8214565720323787967] @1
             <prefixName>"unitLayout"
             <prefixName>"$s$WBitLayout3"
             1)
          c$case_alt[31905][LocalId]
      c$case_alt[31905] :: Clash.Sized.Vector.Vec[8214565720323788085]
                             1
                             (Test.SigType[8214565720323817080]
                                Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
      = <prefixName>"unitLayout"
      <prefixName>"singletonSigFn"
      <prefixName>"singletonSigFn1"
      Clash.Sized.Vector.Cons[8214565720323788088] @1
        @(Test.SigType[8214565720323817080]
            Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
        @0
        _CO_
        elH0[5893][LocalId]
        (Clash.Sized.Vector.Nil[8214565720323788089] @0
           @(Test.SigType[8214565720323817080]
               Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
           _CO_)
      elH0[5893] :: Test.SigType[8214565720323817080]
                      Clash.Sized.Internal.BitVector.Bit[8214565720323788076]
      = case x[6989586621679044907][LocalId] of
          Clash.Sized.Vector.Cons[8214565720323788088] m[5888]
            (_co_[5891] :: GHC.Prim.~#[3674937295934324842]
                             GHC.Types.Nat[3674937295934325064]
                             GHC.Types.Nat[3674937295934325064]
                             1
                             (GHC.TypeNats.+[3674937295934325068] 0 1))
              (el[5890] :: Test.SigType[8214565720323817080]
                             Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
              (rest[5889] :: Clash.Sized.Vector.Vec[8214565720323788085]
                               0
                               (Test.SigType[8214565720323817080]
                                  Clash.Sized.Internal.BitVector.Bit[8214565720323788076])) ->
            el[5890][LocalId]
      x[6989586621679044907] :: Test.SigType[8214565720323817080]
                                  (Clash.Sized.Vector.Vec[8214565720323788085]
                                     1
                                     Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
      = case c$case_scrut[31818][LocalId] of
          GHC.Tuple.(,)[3963167672086036486]
            (c$sel[31901] :: Clash.Sized.Vector.Vec[8214565720323788085]
                               1
                               (Test.SigType[8214565720323817080]
                                  Clash.Sized.Internal.BitVector.Bit[8214565720323788076]))
              (c$wild[31900] :: Clash.Sized.Vector.Vec[8214565720323788085]
                                  (GHC.TypeNats.-[3674937295934325076] 2 1)
                                  (Test.SigType[8214565720323817080]
                                     Clash.Sized.Internal.BitVector.Bit[8214565720323788076])) ->
            c$sel[31901][LocalId]
      elH0[4875] :: Test.SigType[8214565720323817080]
                      Clash.Sized.Internal.BitVector.Bit[8214565720323788076]
      = case y[6989586621679044822][LocalId] of
          Clash.Sized.Vector.Cons[8214565720323788088] m[4870]
            (_co_[4873] :: GHC.Prim.~#[3674937295934324842]
                             GHC.Types.Nat[3674937295934325064]
                             GHC.Types.Nat[3674937295934325064]
                             1
                             (GHC.TypeNats.+[3674937295934325068] 0 1))
              (el[4872] :: Test.SigType[8214565720323817080]
                             Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
              (rest[4871] :: Clash.Sized.Vector.Vec[8214565720323788085]
                               0
                               (Test.SigType[8214565720323817080]
                                  Clash.Sized.Internal.BitVector.Bit[8214565720323788076])) ->
            el[4872][LocalId]
      y[6989586621679044822] :: Test.SigType[8214565720323817080]
                                  (Clash.Sized.Vector.Vec[8214565720323788085]
                                     (GHC.TypeNats.-[3674937295934325076] 2 1)
                                     Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
      = case c$case_scrut[31818][LocalId] of
          GHC.Tuple.(,)[3963167672086036486]
            (c$wild[31822] :: Clash.Sized.Vector.Vec[8214565720323788085]
                                1
                                (Test.SigType[8214565720323817080]
                                   Clash.Sized.Internal.BitVector.Bit[8214565720323788076]))
              (c$sel[31824] :: Clash.Sized.Vector.Vec[8214565720323788085]
                                 (GHC.TypeNats.-[3674937295934325076] 2 1)
                                 (Test.SigType[8214565720323817080]
                                    Clash.Sized.Internal.BitVector.Bit[8214565720323788076])) ->
            c$sel[31824][LocalId]
      c$case_scrut[31818] :: GHC.Tuple.(,)[3746994889972252676]
                               (Clash.Sized.Vector.Vec[8214565720323788085]
                                  1
                                  (Test.SigType[8214565720323817080]
                                     Clash.Sized.Internal.BitVector.Bit[8214565720323788076]))
                               (Clash.Sized.Vector.Vec[8214565720323788085]
                                  (GHC.TypeNats.-[3674937295934325076] 2 1)
                                  (Test.SigType[8214565720323817080]
                                     Clash.Sized.Internal.BitVector.Bit[8214565720323788076]))
      = Clash.Sized.Vector.splitAt @1
          @(GHC.TypeNats.-[3674937295934325076] 2 1)
          @(Test.SigType[8214565720323817080]
              Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
          (Clash.Promoted.Nat.SNat[8214565720323787967] @1
             1)
          c$arg[17344][LocalId]
      elA1[439] :: Clash.Sized.Internal.Index.Index[8214565720323788078]
                     (GHC.TypeNats.+[3674937295934325068] 2 1)
      = <prefixName>"topEntity1_eta"
      case restL0[404][LocalId] of
        Clash.Sized.Vector.Cons[8214565720323788088] m[471]
          (_co_[475] :: GHC.Prim.~#[3674937295934324842]
                          GHC.Types.Nat[3674937295934325064]
                          GHC.Types.Nat[3674937295934325064]
                          1
                          (GHC.TypeNats.+[3674937295934325068] 0 1))
            (el[530] :: Clash.Sized.Internal.Index.Index[8214565720323788078]
                          (GHC.TypeNats.+[3674937295934325068] 2 1))
            (rest[531] :: Clash.Sized.Vector.Vec[8214565720323788085]
                            0
                            (Clash.Sized.Internal.Index.Index[8214565720323788078]
                               (GHC.TypeNats.+[3674937295934325068] 2 1))) ->
          el[530][LocalId]
      elL1[15] :: Clash.Sized.Internal.Index.Index[8214565720323788078]
                    (GHC.TypeNats.+[3674937295934325068] 2 1)
      = case result[31719][LocalId] of
          Clash.Sized.Vector.Cons[8214565720323788088] m[10]
            (_co_[13] :: GHC.Prim.~#[3674937295934324842]
                           GHC.Types.Nat[3674937295934325064]
                           GHC.Types.Nat[3674937295934325064]
                           2
                           (GHC.TypeNats.+[3674937295934325068] 1 1))
              (el[12] :: Clash.Sized.Internal.Index.Index[8214565720323788078]
                           (GHC.TypeNats.+[3674937295934325068] 2 1))
              (rest[11] :: Clash.Sized.Vector.Vec[8214565720323788085]
                             1
                             (Clash.Sized.Internal.Index.Index[8214565720323788078]
                                (GHC.TypeNats.+[3674937295934325068] 2 1))) ->
            el[12][LocalId]
      result[31719] :: Clash.Sized.Vector.Vec[8214565720323788085]
                         2
                         (Clash.Sized.Internal.Index.Index[8214565720323788078]
                            (GHC.TypeNats.+[3674937295934325068] 2 1))
      = Clash.Sized.Vector.Cons[8214565720323788088]
          @2
          @(Clash.Sized.Internal.Index.Index[8214565720323788078]
              (GHC.TypeNats.+[3674937295934325068] 2 1))
          @1
          _CO_
          c$rest_app_arg[31716][LocalId]
          c$rest_app_arg[31718][LocalId]
      c$rest_app_arg[31718] :: Clash.Sized.Vector.Vec[8214565720323788085]
                                 1
                                 (Clash.Sized.Internal.Index.Index[8214565720323788078]
                                    (GHC.TypeNats.+[3674937295934325068] 2 1))
      = Clash.Sized.Vector.Cons[8214565720323788088]
          @1
          @(Clash.Sized.Internal.Index.Index[8214565720323788078]
              (GHC.TypeNats.+[3674937295934325068] 2 1))
          @0
          _CO_
          c$rest_app_arg[31717][LocalId]
          (Clash.Sized.Vector.Nil[8214565720323788089] @0
             @(Clash.Sized.Internal.Index.Index[8214565720323788078]
                 (GHC.TypeNats.+[3674937295934325068] 2 1))
             _CO_)
      c$rest_app_arg[31717] :: Clash.Sized.Internal.Index.Index[8214565720323788078]
                                 (GHC.TypeNats.+[3674937295934325068] 2 1)
      = <prefixName>"$s$fEnumIndex_$csucc"
          <prefixName>"$s$fEnumIndex_$csucc_lvl11"
          Clash.Sized.Internal.Index.+#
          @(GHC.TypeNats.+[3674937295934325068] 2 1)
          (Clash.Transformations.removedArg
             @GHC.Natural.Natural[3674937295934324786])
          elA1[33][LocalId]
          (Clash.Sized.Internal.Index.fromInteger#
             @(GHC.TypeNats.+[3674937295934325068] 2 1)
             3
             1)
      elA1[33] :: Clash.Sized.Internal.Index.Index[8214565720323788078]
                    (GHC.TypeNats.+[3674937295934325068] 2 1)
      = case restA0[26][LocalId] of
          Clash.Sized.Vector.Cons[8214565720323788088] m[28]
            (_co_[49] :: GHC.Prim.~#[3674937295934324842]
                           GHC.Types.Nat[3674937295934325064]
                           GHC.Types.Nat[3674937295934325064]
                           1
                           (GHC.TypeNats.+[3674937295934325068] 0 1))
              (el[30] :: Clash.Sized.Internal.Index.Index[8214565720323788078]
                           (GHC.TypeNats.+[3674937295934325068] 2 1))
              (rest[29] :: Clash.Sized.Vector.Vec[8214565720323788085]
                             0
                             (Clash.Sized.Internal.Index.Index[8214565720323788078]
                                (GHC.TypeNats.+[3674937295934325068] 2 1))) ->
            el[30][LocalId]
      restA0[26] :: Clash.Sized.Vector.Vec[8214565720323788085]
                      1
                      (Clash.Sized.Internal.Index.Index[8214565720323788078]
                         (GHC.TypeNats.+[3674937295934325068] 2 1))
      = Clash.Sized.Vector.lazyV @1
          @(Clash.Sized.Internal.Index.Index[8214565720323788078]
              (GHC.TypeNats.+[3674937295934325068] 2 1))
          (Clash.Transformations.removedArg
             @GHC.Natural.Natural[3674937295934324786])
          restL0[404][LocalId]
      restL0[404] :: Clash.Sized.Vector.Vec[8214565720323788085]
                       1
                       (Clash.Sized.Internal.Index.Index[8214565720323788078]
                          (GHC.TypeNats.+[3674937295934325068] 2 1))
      = case <prefixName>"layout"
          <prefixName>"layout_$smkPos"
          result[31733][LocalId] of
          Clash.Sized.Vector.Cons[8214565720323788088] m[400]
            (_co_[403] :: GHC.Prim.~#[3674937295934324842]
                            GHC.Types.Nat[3674937295934325064]
                            GHC.Types.Nat[3674937295934325064]
                            2
                            (GHC.TypeNats.+[3674937295934325068] 1 1))
              (el[402] :: Clash.Sized.Internal.Index.Index[8214565720323788078]
                            (GHC.TypeNats.+[3674937295934325068] 2 1))
              (rest[401] :: Clash.Sized.Vector.Vec[8214565720323788085]
                              1
                              (Clash.Sized.Internal.Index.Index[8214565720323788078]
                                 (GHC.TypeNats.+[3674937295934325068] 2 1))) ->
            rest[401][LocalId]
      c$rest_app_arg[31716] :: Clash.Sized.Internal.Index.Index[8214565720323788078]
                                 (GHC.TypeNats.+[3674937295934325068] 2 1)
      = <prefixName>"$s$fEnumIndex_$csucc"
          <prefixName>"$s$fEnumIndex_$csucc_lvl11"
          Clash.Sized.Internal.Index.+#
          @(GHC.TypeNats.+[3674937295934325068] 2 1)
          (Clash.Transformations.removedArg
             @GHC.Natural.Natural[3674937295934324786])
          elH0[279][LocalId]
          (Clash.Sized.Internal.Index.fromInteger#
             @(GHC.TypeNats.+[3674937295934325068] 2 1)
             3
             1)
      elH0[279] :: Clash.Sized.Internal.Index.Index[8214565720323788078]
                     (GHC.TypeNats.+[3674937295934325068] 2 1)
      = case <prefixName>"layout"
          <prefixName>"layout_$smkPos"
          result[31733][LocalId] of
          Clash.Sized.Vector.Cons[8214565720323788088] m[274]
            (_co_[277] :: GHC.Prim.~#[3674937295934324842]
                            GHC.Types.Nat[3674937295934325064]
                            GHC.Types.Nat[3674937295934325064]
                            2
                            (GHC.TypeNats.+[3674937295934325068] 1 1))
              (el[276] :: Clash.Sized.Internal.Index.Index[8214565720323788078]
                            (GHC.TypeNats.+[3674937295934325068] 2 1))
              (rest[275] :: Clash.Sized.Vector.Vec[8214565720323788085]
                              1
                              (Clash.Sized.Internal.Index.Index[8214565720323788078]
                                 (GHC.TypeNats.+[3674937295934325068] 2 1))) ->
            el[276][LocalId]
      result[31733] :: Clash.Sized.Vector.Vec[8214565720323788085]
                         2
                         (Clash.Sized.Internal.Index.Index[8214565720323788078]
                            (GHC.TypeNats.+[3674937295934325068] 2 1))
      = Clash.Sized.Vector.Cons[8214565720323788088]
          @2
          @(Clash.Sized.Internal.Index.Index[8214565720323788078]
              (GHC.TypeNats.+[3674937295934325068] 2 1))
          @1
          _CO_
          (Clash.Sized.Internal.Index.fromInteger#
             @(GHC.TypeNats.+[3674937295934325068] 2 1)
             3
             0)
          c$xs_app_arg[31732][LocalId]
      c$xs_app_arg[31732] :: Clash.Sized.Vector.Vec[8214565720323788085]
                               1
                               (Clash.Sized.Internal.Index.Index[8214565720323788078]
                                  (GHC.TypeNats.+[3674937295934325068] 2 1))
      = Clash.Sized.Vector.Cons[8214565720323788088]
          @1
          @(Clash.Sized.Internal.Index.Index[8214565720323788078]
              (GHC.TypeNats.+[3674937295934325068] 2 1))
          @0
          _CO_
          elL1[15][LocalId]
          (Clash.Sized.Vector.Nil[8214565720323788089] @0
             @(Clash.Sized.Internal.Index.Index[8214565720323788078]
                 (GHC.TypeNats.+[3674937295934325068] 2 1))
             _CO_)
    in result[31996][LocalId]
    Result:
    letrec
      result[31996] :: Test.SigType[8214565720323817080]
                         (Clash.Sized.Vector.Vec[8214565720323788085]
                            2
                            Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
      = case Clash.Sized.Internal.Index.lt#
               @(GHC.TypeNats.+[3674937295934325068] 2 1)
               (case <prefixName>"layout"
                  <prefixName>"layout_$smkPos"
                  result[31733][LocalId] of
                  Clash.Sized.Vector.Cons[8214565720323788088] m[274]
                    (_co_[277] :: GHC.Prim.~#[3674937295934324842]
                                    GHC.Types.Nat[3674937295934325064]
                                    GHC.Types.Nat[3674937295934325064]
                                    2
                                    (GHC.TypeNats.+[3674937295934325068] 1 1))
                      (el[276] :: Clash.Sized.Internal.Index.Index[8214565720323788078]
                                    (GHC.TypeNats.+[3674937295934325068] 2 1))
                      (rest[275] :: Clash.Sized.Vector.Vec[8214565720323788085]
                                      1
                                      (Clash.Sized.Internal.Index.Index[8214565720323788078]
                                         (GHC.TypeNats.+[3674937295934325068]
                                            2
                                            1))) ->
                    el[276][LocalId])
               (Clash.Sized.Internal.Index.fromInteger# @3 3
                  0) of
          GHC.Types.False[3891110078048108556]  ->
            result[31849][LocalId]
          GHC.Types.True[3891110078048108589]  ->
            result[31994][LocalId]
      result[31994] :: Test.SigType[8214565720323817080]
                         (Clash.Sized.Vector.Vec[8214565720323788085]
                            2
                            Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
      = case c$case_scrut[31848][LocalId] of
          GHC.Types.False[3891110078048108556]  ->
            Clash.Sized.Vector.Cons[8214565720323788088] @2
              @(Test.SigType[8214565720323817080]
                  Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
              @1
              _CO_
              <prefixName>"unitLayout"
              <prefixName>"headSigFn"
              (case x[6989586621679044914][LocalId] of
                 Clash.Sized.Vector.Cons[8214565720323788088] m[11008]
                   (_co_[11011] :: GHC.Prim.~#[3674937295934324842]
                                     GHC.Types.Nat[3674937295934325064]
                                     GHC.Types.Nat[3674937295934325064]
                                     1
                                     (GHC.TypeNats.+[3674937295934325068] 0 1))
                     (el[11010] :: Test.SigType[8214565720323817080]
                                     Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
                     (rest[11009] :: Clash.Sized.Vector.Vec[8214565720323788085]
                                       0
                                       (Test.SigType[8214565720323817080]
                                          Clash.Sized.Internal.BitVector.Bit[8214565720323788076])) ->
                   el[11010][LocalId])
              (Clash.Sized.Vector.Cons[8214565720323788088] @1
                 @(Test.SigType[8214565720323817080]
                     Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
                 @0
                 _CO_
                 <prefixName>"layout_$svoidLayout"
                 <prefixName>"layout1"
                 <prefixName>"layout2"
                 <prefixName>"layout3"
                 Clash.Sized.Internal.BitVector.low
                 (Clash.Sized.Vector.Nil[8214565720323788089] @0
                    @(Test.SigType[8214565720323817080]
                        Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
                    _CO_))
          GHC.Types.True[3891110078048108589]  ->
            Clash.Sized.Vector.Cons[8214565720323788088] @2
              @(Test.SigType[8214565720323817080]
                  Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
              @1
              _CO_
              <prefixName>"unitLayout"
              <prefixName>"headSigFn"
              (case x[6989586621679044936][LocalId] of
                 Clash.Sized.Vector.Cons[8214565720323788088] m[11208]
                   (_co_[11211] :: GHC.Prim.~#[3674937295934324842]
                                     GHC.Types.Nat[3674937295934325064]
                                     GHC.Types.Nat[3674937295934325064]
                                     1
                                     (GHC.TypeNats.+[3674937295934325068] 0 1))
                     (el[11210] :: Test.SigType[8214565720323817080]
                                     Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
                     (rest[11209] :: Clash.Sized.Vector.Vec[8214565720323788085]
                                       0
                                       (Test.SigType[8214565720323817080]
                                          Clash.Sized.Internal.BitVector.Bit[8214565720323788076])) ->
                   el[11210][LocalId])
              (Clash.Sized.Vector.Cons[8214565720323788088] @1
                 @(Test.SigType[8214565720323817080]
                     Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
                 @0
                 _CO_
                 <prefixName>"unitLayout"
                 <prefixName>"headSigFn"
                 (case y[6989586621679044938][LocalId] of
                    Clash.Sized.Vector.Cons[8214565720323788088] m[15328]
                      (_co_[15331] :: GHC.Prim.~#[3674937295934324842]
                                        GHC.Types.Nat[3674937295934325064]
                                        GHC.Types.Nat[3674937295934325064]
                                        1
                                        (GHC.TypeNats.+[3674937295934325068] 0 1))
                        (el[15330] :: Test.SigType[8214565720323817080]
                                        Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
                        (rest[15329] :: Clash.Sized.Vector.Vec[8214565720323788085]
                                          0
                                          (Test.SigType[8214565720323817080]
                                             Clash.Sized.Internal.BitVector.Bit[8214565720323788076])) ->
                      el[15330][LocalId])
                 (Clash.Sized.Vector.Nil[8214565720323788089] @0
                    @(Test.SigType[8214565720323817080]
                        Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
                    _CO_))
      result[31849] :: Test.SigType[8214565720323817080]
                         (Clash.Sized.Vector.Vec[8214565720323788085]
                            2
                            Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
      = case c$case_scrut[31848][LocalId] of
          GHC.Types.False[3891110078048108556]  ->
            Clash.Sized.Vector.Cons[8214565720323788088] @2
              @(Test.SigType[8214565720323817080]
                  Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
              @1
              _CO_
              <prefixName>"layout_$svoidLayout"
              <prefixName>"layout1"
              <prefixName>"layout2"
              <prefixName>"layout3"
              Clash.Sized.Internal.BitVector.low
              (Clash.Sized.Vector.Cons[8214565720323788088] @1
                 @(Test.SigType[8214565720323817080]
                     Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
                 @0
                 _CO_
                 <prefixName>"layout_$svoidLayout"
                 <prefixName>"layout1"
                 <prefixName>"layout2"
                 <prefixName>"layout3"
                 Clash.Sized.Internal.BitVector.low
                 (Clash.Sized.Vector.Nil[8214565720323788089] @0
                    @(Test.SigType[8214565720323817080]
                        Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
                    _CO_))
          GHC.Types.True[3891110078048108589]  ->
            Clash.Sized.Vector.Cons[8214565720323788088] @2
              @(Test.SigType[8214565720323817080]
                  Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
              @1
              _CO_
              <prefixName>"layout_$svoidLayout"
              <prefixName>"layout1"
              <prefixName>"layout2"
              <prefixName>"layout3"
              Clash.Sized.Internal.BitVector.low
              (Clash.Sized.Vector.Cons[8214565720323788088] @1
                 @(Test.SigType[8214565720323817080]
                     Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
                 @0
                 _CO_
                 <prefixName>"unitLayout"
                 <prefixName>"headSigFn"
                 (case y[6989586621679044887][LocalId] of
                    Clash.Sized.Vector.Cons[8214565720323788088] m[14304]
                      (_co_[14307] :: GHC.Prim.~#[3674937295934324842]
                                        GHC.Types.Nat[3674937295934325064]
                                        GHC.Types.Nat[3674937295934325064]
                                        1
                                        (GHC.TypeNats.+[3674937295934325068] 0 1))
                        (el[14306] :: Test.SigType[8214565720323817080]
                                        Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
                        (rest[14305] :: Clash.Sized.Vector.Vec[8214565720323788085]
                                          0
                                          (Test.SigType[8214565720323817080]
                                             Clash.Sized.Internal.BitVector.Bit[8214565720323788076])) ->
                      el[14306][LocalId])
                 (Clash.Sized.Vector.Nil[8214565720323788089] @0
                    @(Test.SigType[8214565720323817080]
                        Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
                    _CO_))
      c$case_scrut[31848] :: GHC.Types.Bool[3674937295934324744]
      = Clash.Sized.Internal.Index.lt#
          @(GHC.TypeNats.+[3674937295934325068] 2 1)
          <prefixName>"topEntity1_eta"
          (case (case <prefixName>"layout"
                   <prefixName>"layout_$smkPos"
                   result[31733][LocalId] of
                   Clash.Sized.Vector.Cons[8214565720323788088] m[400]
                     (_co_[403] :: GHC.Prim.~#[3674937295934324842]
                                     GHC.Types.Nat[3674937295934325064]
                                     GHC.Types.Nat[3674937295934325064]
                                     2
                                     (GHC.TypeNats.+[3674937295934325068] 1 1))
                       (el[402] :: Clash.Sized.Internal.Index.Index[8214565720323788078]
                                     (GHC.TypeNats.+[3674937295934325068] 2 1))
                       (rest[401] :: Clash.Sized.Vector.Vec[8214565720323788085]
                                       1
                                       (Clash.Sized.Internal.Index.Index[8214565720323788078]
                                          (GHC.TypeNats.+[3674937295934325068]
                                             2
                                             1))) ->
                     rest[401][LocalId]) of
             Clash.Sized.Vector.Cons[8214565720323788088] m[471]
               (_co_[475] :: GHC.Prim.~#[3674937295934324842]
                               GHC.Types.Nat[3674937295934325064]
                               GHC.Types.Nat[3674937295934325064]
                               1
                               (GHC.TypeNats.+[3674937295934325068] 0 1))
                 (el[530] :: Clash.Sized.Internal.Index.Index[8214565720323788078]
                               (GHC.TypeNats.+[3674937295934325068] 2 1))
                 (rest[531] :: Clash.Sized.Vector.Vec[8214565720323788085]
                                 0
                                 (Clash.Sized.Internal.Index.Index[8214565720323788078]
                                    (GHC.TypeNats.+[3674937295934325068] 2 1))) ->
               el[530][LocalId])
          (Clash.Sized.Internal.Index.fromInteger# @3 3 0)
      y[6989586621679044938] :: Test.SigType[8214565720323817080]
                                  (Clash.Sized.Vector.Vec[8214565720323788085]
                                     1
                                     Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
      = case c$case_scrut[31986][LocalId] of
          GHC.Tuple.(,)[3963167672086036486]
            (c$wild[31990] :: Clash.Sized.Vector.Vec[8214565720323788085]
                                1
                                (Test.SigType[8214565720323817080]
                                   Clash.Sized.Internal.BitVector.Bit[8214565720323788076]))
              (c$sel[31992] :: Clash.Sized.Vector.Vec[8214565720323788085]
                                 1
                                 (Test.SigType[8214565720323817080]
                                    Clash.Sized.Internal.BitVector.Bit[8214565720323788076])) ->
            c$sel[31992][LocalId]
      y[6989586621679044887] :: Test.SigType[8214565720323817080]
                                  (Clash.Sized.Vector.Vec[8214565720323788085]
                                     1
                                     Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
      = case Clash.Sized.Vector.splitAt @0 @1
               @(Test.SigType[8214565720323817080]
                   Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
               (Clash.Promoted.Nat.SNat[8214565720323787967] @0
                  <prefixName>"layout_$svoidLayout"
                  <prefixName>"$s$WBitLayout1"
                  0)
               <prefixName>"unitLayout"
               <prefixName>"singletonSigFn"
               <prefixName>"singletonSigFn1"
               (Clash.Sized.Vector.Cons[8214565720323788088] @1
                  @(Test.SigType[8214565720323817080]
                      Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
                  @0
                  _CO_
                  (case y[6989586621679044822][LocalId] of
                     Clash.Sized.Vector.Cons[8214565720323788088] m[4870]
                       (_co_[4873] :: GHC.Prim.~#[3674937295934324842]
                                        GHC.Types.Nat[3674937295934325064]
                                        GHC.Types.Nat[3674937295934325064]
                                        1
                                        (GHC.TypeNats.+[3674937295934325068] 0 1))
                         (el[4872] :: Test.SigType[8214565720323817080]
                                        Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
                         (rest[4871] :: Clash.Sized.Vector.Vec[8214565720323788085]
                                          0
                                          (Test.SigType[8214565720323817080]
                                             Clash.Sized.Internal.BitVector.Bit[8214565720323788076])) ->
                       el[4872][LocalId])
                  (Clash.Sized.Vector.Nil[8214565720323788089] @0
                     @(Test.SigType[8214565720323817080]
                         Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
                     _CO_)) of
          GHC.Tuple.(,)[3963167672086036486]
            (c$wild[31844] :: Clash.Sized.Vector.Vec[8214565720323788085]
                                0
                                (Test.SigType[8214565720323817080]
                                   Clash.Sized.Internal.BitVector.Bit[8214565720323788076]))
              (c$sel[31846] :: Clash.Sized.Vector.Vec[8214565720323788085]
                                 1
                                 (Test.SigType[8214565720323817080]
                                    Clash.Sized.Internal.BitVector.Bit[8214565720323788076])) ->
            c$sel[31846][LocalId]
      x[6989586621679044936] :: Test.SigType[8214565720323817080]
                                  (Clash.Sized.Vector.Vec[8214565720323788085]
                                     1
                                     Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
      = case c$case_scrut[31986][LocalId] of
          GHC.Tuple.(,)[3963167672086036486]
            (c$sel[31989] :: Clash.Sized.Vector.Vec[8214565720323788085]
                               1
                               (Test.SigType[8214565720323817080]
                                  Clash.Sized.Internal.BitVector.Bit[8214565720323788076]))
              (c$wild[31988] :: Clash.Sized.Vector.Vec[8214565720323788085]
                                  1
                                  (Test.SigType[8214565720323817080]
                                     Clash.Sized.Internal.BitVector.Bit[8214565720323788076])) ->
            c$sel[31989][LocalId]
      c$case_scrut[31986] :: GHC.Tuple.(,)[3746994889972252676]
                               (Clash.Sized.Vector.Vec[8214565720323788085]
                                  1
                                  (Test.SigType[8214565720323817080]
                                     Clash.Sized.Internal.BitVector.Bit[8214565720323788076]))
                               (Clash.Sized.Vector.Vec[8214565720323788085]
                                  1
                                  (Test.SigType[8214565720323817080]
                                     Clash.Sized.Internal.BitVector.Bit[8214565720323788076]))
      = Clash.Sized.Vector.splitAt @1 @1
          @(Test.SigType[8214565720323817080]
              Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
          (Clash.Promoted.Nat.SNat[8214565720323787967] @1
             <prefixName>"unitLayout"
             <prefixName>"$s$WBitLayout3"
             1)
          (Clash.Sized.Vector.Cons[8214565720323788088] @2
             @(Test.SigType[8214565720323817080]
                 Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
             @1
             _CO_
             <prefixName>"unitLayout"
             <prefixName>"singletonSigFn"
             <prefixName>"singletonSigFn1"
             (case x[6989586621679044907][LocalId] of
                Clash.Sized.Vector.Cons[8214565720323788088] m[5888]
                  (_co_[5891] :: GHC.Prim.~#[3674937295934324842]
                                   GHC.Types.Nat[3674937295934325064]
                                   GHC.Types.Nat[3674937295934325064]
                                   1
                                   (GHC.TypeNats.+[3674937295934325068] 0 1))
                    (el[5890] :: Test.SigType[8214565720323817080]
                                   Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
                    (rest[5889] :: Clash.Sized.Vector.Vec[8214565720323788085]
                                     0
                                     (Test.SigType[8214565720323817080]
                                        Clash.Sized.Internal.BitVector.Bit[8214565720323788076])) ->
                  el[5890][LocalId])
             <prefixName>"unitLayout"
             <prefixName>"singletonSigFn"
             <prefixName>"singletonSigFn1"
             (Clash.Sized.Vector.Cons[8214565720323788088] @1
                @(Test.SigType[8214565720323817080]
                    Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
                @0
                _CO_
                (case y[6989586621679044822][LocalId] of
                   Clash.Sized.Vector.Cons[8214565720323788088] m[4870]
                     (_co_[4873] :: GHC.Prim.~#[3674937295934324842]
                                      GHC.Types.Nat[3674937295934325064]
                                      GHC.Types.Nat[3674937295934325064]
                                      1
                                      (GHC.TypeNats.+[3674937295934325068] 0 1))
                       (el[4872] :: Test.SigType[8214565720323817080]
                                      Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
                       (rest[4871] :: Clash.Sized.Vector.Vec[8214565720323788085]
                                        0
                                        (Test.SigType[8214565720323817080]
                                           Clash.Sized.Internal.BitVector.Bit[8214565720323788076])) ->
                     el[4872][LocalId])
                (Clash.Sized.Vector.Nil[8214565720323788089] @0
                   @(Test.SigType[8214565720323817080]
                       Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
                   _CO_)))
      x[6989586621679044914] :: Test.SigType[8214565720323817080]
                                  (Clash.Sized.Vector.Vec[8214565720323788085]
                                     1
                                     Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
      = case Clash.Sized.Vector.splitAt @1 @0
               @(Test.SigType[8214565720323817080]
                   Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
               (Clash.Promoted.Nat.SNat[8214565720323787967] @1
                  <prefixName>"unitLayout"
                  <prefixName>"$s$WBitLayout3"
                  1)
               <prefixName>"unitLayout"
               <prefixName>"singletonSigFn"
               <prefixName>"singletonSigFn1"
               (Clash.Sized.Vector.Cons[8214565720323788088] @1
                  @(Test.SigType[8214565720323817080]
                      Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
                  @0
                  _CO_
                  (case x[6989586621679044907][LocalId] of
                     Clash.Sized.Vector.Cons[8214565720323788088] m[5888]
                       (_co_[5891] :: GHC.Prim.~#[3674937295934324842]
                                        GHC.Types.Nat[3674937295934325064]
                                        GHC.Types.Nat[3674937295934325064]
                                        1
                                        (GHC.TypeNats.+[3674937295934325068] 0 1))
                         (el[5890] :: Test.SigType[8214565720323817080]
                                        Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
                         (rest[5889] :: Clash.Sized.Vector.Vec[8214565720323788085]
                                          0
                                          (Test.SigType[8214565720323817080]
                                             Clash.Sized.Internal.BitVector.Bit[8214565720323788076])) ->
                       el[5890][LocalId])
                  (Clash.Sized.Vector.Nil[8214565720323788089] @0
                     @(Test.SigType[8214565720323817080]
                         Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
                     _CO_)) of
          GHC.Tuple.(,)[3963167672086036486]
            (c$sel[31922] :: Clash.Sized.Vector.Vec[8214565720323788085]
                               1
                               (Test.SigType[8214565720323817080]
                                  Clash.Sized.Internal.BitVector.Bit[8214565720323788076]))
              (c$wild[31921] :: Clash.Sized.Vector.Vec[8214565720323788085]
                                  0
                                  (Test.SigType[8214565720323817080]
                                     Clash.Sized.Internal.BitVector.Bit[8214565720323788076])) ->
            c$sel[31922][LocalId]
      x[6989586621679044907] :: Test.SigType[8214565720323817080]
                                  (Clash.Sized.Vector.Vec[8214565720323788085]
                                     1
                                     Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
      = case c$case_scrut[31818][LocalId] of
          GHC.Tuple.(,)[3963167672086036486]
            (c$sel[31901] :: Clash.Sized.Vector.Vec[8214565720323788085]
                               1
                               (Test.SigType[8214565720323817080]
                                  Clash.Sized.Internal.BitVector.Bit[8214565720323788076]))
              (c$wild[31900] :: Clash.Sized.Vector.Vec[8214565720323788085]
                                  (GHC.TypeNats.-[3674937295934325076] 2 1)
                                  (Test.SigType[8214565720323817080]
                                     Clash.Sized.Internal.BitVector.Bit[8214565720323788076])) ->
            c$sel[31901][LocalId]
      y[6989586621679044822] :: Test.SigType[8214565720323817080]
                                  (Clash.Sized.Vector.Vec[8214565720323788085]
                                     (GHC.TypeNats.-[3674937295934325076] 2 1)
                                     Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
      = case c$case_scrut[31818][LocalId] of
          GHC.Tuple.(,)[3963167672086036486]
            (c$wild[31822] :: Clash.Sized.Vector.Vec[8214565720323788085]
                                1
                                (Test.SigType[8214565720323817080]
                                   Clash.Sized.Internal.BitVector.Bit[8214565720323788076]))
              (c$sel[31824] :: Clash.Sized.Vector.Vec[8214565720323788085]
                                 (GHC.TypeNats.-[3674937295934325076] 2 1)
                                 (Test.SigType[8214565720323817080]
                                    Clash.Sized.Internal.BitVector.Bit[8214565720323788076])) ->
            c$sel[31824][LocalId]
      c$case_scrut[31818] :: GHC.Tuple.(,)[3746994889972252676]
                               (Clash.Sized.Vector.Vec[8214565720323788085]
                                  1
                                  (Test.SigType[8214565720323817080]
                                     Clash.Sized.Internal.BitVector.Bit[8214565720323788076]))
                               (Clash.Sized.Vector.Vec[8214565720323788085]
                                  (GHC.TypeNats.-[3674937295934325076] 2 1)
                                  (Test.SigType[8214565720323817080]
                                     Clash.Sized.Internal.BitVector.Bit[8214565720323788076]))
      = Clash.Sized.Vector.splitAt @1
          @(GHC.TypeNats.-[3674937295934325076] 2 1)
          @(Test.SigType[8214565720323817080]
              Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
          (Clash.Promoted.Nat.SNat[8214565720323787967] @1
             1)
          c$arg[17344][LocalId]
      result[31733] :: Clash.Sized.Vector.Vec[8214565720323788085]
                         2
                         (Clash.Sized.Internal.Index.Index[8214565720323788078]
                            (GHC.TypeNats.+[3674937295934325068] 2 1))
      = Clash.Sized.Vector.Cons[8214565720323788088]
          @2
          @(Clash.Sized.Internal.Index.Index[8214565720323788078]
              (GHC.TypeNats.+[3674937295934325068] 2 1))
          @1
          _CO_
          (Clash.Sized.Internal.Index.fromInteger#
             @(GHC.TypeNats.+[3674937295934325068] 2 1)
             3
             0)
          (Clash.Sized.Vector.Cons[8214565720323788088] @1
             @(Clash.Sized.Internal.Index.Index[8214565720323788078]
                 (GHC.TypeNats.+[3674937295934325068] 2 1))
             @0
             _CO_
             (case (Clash.Sized.Vector.Cons[8214565720323788088]
                      @2
                      @(Clash.Sized.Internal.Index.Index[8214565720323788078]
                          (GHC.TypeNats.+[3674937295934325068] 2 1))
                      @1
                      _CO_
                      (<prefixName>"$s$fEnumIndex_$csucc"
                         <prefixName>"$s$fEnumIndex_$csucc_lvl11"
                         Clash.Sized.Internal.Index.+#
                         @(GHC.TypeNats.+[3674937295934325068] 2 1)
                         (Clash.Transformations.removedArg
                            @GHC.Natural.Natural[3674937295934324786])
                         elH0[279][LocalId]
                         (Clash.Sized.Internal.Index.fromInteger#
                            @(GHC.TypeNats.+[3674937295934325068] 2 1)
                            3
                            1))
                      (Clash.Sized.Vector.Cons[8214565720323788088] @1
                         @(Clash.Sized.Internal.Index.Index[8214565720323788078]
                             (GHC.TypeNats.+[3674937295934325068] 2 1))
                         @0
                         _CO_
                         (<prefixName>"$s$fEnumIndex_$csucc"
                            <prefixName>"$s$fEnumIndex_$csucc_lvl11"
                            Clash.Sized.Internal.Index.+#
                            @(GHC.TypeNats.+[3674937295934325068] 2 1)
                            (Clash.Transformations.removedArg
                               @GHC.Natural.Natural[3674937295934324786])
                            (case (Clash.Sized.Vector.lazyV @1
                                     @(Clash.Sized.Internal.Index.Index[8214565720323788078]
                                         (GHC.TypeNats.+[3674937295934325068] 2 1))
                                     (Clash.Transformations.removedArg
                                        @GHC.Natural.Natural[3674937295934324786])
                                     (case <prefixName>"layout"
                                        <prefixName>"layout_$smkPos"
                                        result[31733][LocalId] of
                                        Clash.Sized.Vector.Cons[8214565720323788088] m[400]
                                          (_co_[403] :: GHC.Prim.~#[3674937295934324842]
                                                          GHC.Types.Nat[3674937295934325064]
                                                          GHC.Types.Nat[3674937295934325064]
                                                          2
                                                          (GHC.TypeNats.+[3674937295934325068]
                                                             1
                                                             1))
                                            (el[402] :: Clash.Sized.Internal.Index.Index[8214565720323788078]
                                                          (GHC.TypeNats.+[3674937295934325068]
                                                             2
                                                             1))
                                            (rest[401] :: Clash.Sized.Vector.Vec[8214565720323788085]
                                                            1
                                                            (Clash.Sized.Internal.Index.Index[8214565720323788078]
                                                               (GHC.TypeNats.+[3674937295934325068]
                                                                  2
                                                                  1))) ->
                                          rest[401][LocalId])) of
                               Clash.Sized.Vector.Cons[8214565720323788088] m[28]
                                 (_co_[49] :: GHC.Prim.~#[3674937295934324842]
                                                GHC.Types.Nat[3674937295934325064]
                                                GHC.Types.Nat[3674937295934325064]
                                                1
                                                (GHC.TypeNats.+[3674937295934325068]
                                                   0
                                                   1))
                                   (el[30] :: Clash.Sized.Internal.Index.Index[8214565720323788078]
                                                (GHC.TypeNats.+[3674937295934325068]
                                                   2
                                                   1))
                                   (rest[29] :: Clash.Sized.Vector.Vec[8214565720323788085]
                                                  0
                                                  (Clash.Sized.Internal.Index.Index[8214565720323788078]
                                                     (GHC.TypeNats.+[3674937295934325068]
                                                        2
                                                        1))) ->
                                 el[30][LocalId])
                            (Clash.Sized.Internal.Index.fromInteger#
                               @(GHC.TypeNats.+[3674937295934325068] 2 1)
                               3
                               1))
                         (Clash.Sized.Vector.Nil[8214565720323788089] @0
                            @(Clash.Sized.Internal.Index.Index[8214565720323788078]
                                (GHC.TypeNats.+[3674937295934325068] 2 1))
                            _CO_))) of
                Clash.Sized.Vector.Cons[8214565720323788088] m[10]
                  (_co_[13] :: GHC.Prim.~#[3674937295934324842]
                                 GHC.Types.Nat[3674937295934325064]
                                 GHC.Types.Nat[3674937295934325064]
                                 2
                                 (GHC.TypeNats.+[3674937295934325068] 1 1))
                    (el[12] :: Clash.Sized.Internal.Index.Index[8214565720323788078]
                                 (GHC.TypeNats.+[3674937295934325068] 2 1))
                    (rest[11] :: Clash.Sized.Vector.Vec[8214565720323788085]
                                   1
                                   (Clash.Sized.Internal.Index.Index[8214565720323788078]
                                      (GHC.TypeNats.+[3674937295934325068] 2 1))) ->
                  el[12][LocalId])
             (Clash.Sized.Vector.Nil[8214565720323788089] @0
                @(Clash.Sized.Internal.Index.Index[8214565720323788078]
                    (GHC.TypeNats.+[3674937295934325068] 2 1))
                _CO_))
    in result[31996][LocalId]
    It introduces free variables.
    Before: c$arg[17344] :: Test.SigType[8214565720323817080]
                      (Clash.Sized.Vector.Vec[8214565720323788085]
                         2
                         Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
    After: elH0[279] :: Clash.Sized.Internal.Index.Index[8214565720323788078]
                   (GHC.TypeNats.+[3674937295934325068] 2 1)
    c$arg[17344] :: Test.SigType[8214565720323817080]
                      (Clash.Sized.Vector.Vec[8214565720323788085]
                         2
                         Clash.Sized.Internal.BitVector.Bit[8214565720323788076])
    CallStack (from HasCallStack):
      error, called at src/Clash/Rewrite/Util.hs:232:13 in clash-lib-1.3.0-inplace:Clash.Rewrite.Util

```

### PR DESCRIPTION
**Pull request by martijnbastiaan**
Fix #1337

### CODE REVIEW

**Comment by martijnbastiaan** [comment]
Ah, you're right of course :). Fixed!

**Comment by christiaanb** [comment]
I still have to think about this really hard, as I don't understand why this solves the issue, given that `inlineBndrsCleanup` traverses the bindings we do _not_ inline. i.e. why does building the substitution for one let-binding-we-do-not-inline, need to be the start of the substitution for another let-binding-we-do-not-inline.

**Comment by martijnbastiaan** [comment]
@christiaanb I believe this should implement the solution we discussed.

File: clash-lib/src/Clash/Normalize/Transformations.hs [hunk 1]
```diff
@@ -2558,23 +2577,29 @@ inlineBndrsCleanup isN origInl = go
...
-    -- to inline them.
-    [ (v,e) | ((v,e),_,Rec) <- eltsVarEnv doneInl ]
-  go !doneInl (((v,e),eFVs):il) =
-    let (sM,_,doneInl1) = foldlWithUniqueVarEnv'
+    -- to inline them. Furthermore, for every recursive binder there might still
+    -- be non-inlined variables left, see #1337.
+    flip map [ (ve, eFvs) | (ve,eFvs,Rec) <- eltsVarEnv doneInl ] $ \((v, e), eFvs) ->
+      let
+        (substM, _, _) = foldlWithUniqueVarEnv'
+                           (reduceBindersCleanup isN origInl)
```
Comment (christiaanb) [inline clash-lib/src/Clash/Normalize/Transformations.hs:2585]: Shouldn't we pass in en empty varenv instead of `origInl`? I mean... at this point we don't want to lookup things in `origInl` anymore.

File: clash-lib/tests/Test/Clash/Rewrite.hs [hunk 2]
```diff
@@ -0,0 +1,301 @@
...
+  -> C.Term
+  -- ^ Term to transform
+  -> C.Term
+runSingleTransformation rwEnv rwState is trans term = t
+ where (t, _, _) = runR (runRewrite "" is trans term) rwEnv rwState
+
+-- | Run a single transformation with an empty environment and empty
+-- InScopeSet. See Default instances ^ to inspect the precise definition of
+-- "empty".
+runSingleTransformationDef :: Default extra => Rewrite extra -> C.Term -> C.Term
```
Comment (christiaanb) [inline clash-lib/tests/Test/Clash/Rewrite.hs:127]: This functions should come with a BIG WARNING telling the developer not to use it for transformations that:
1. Evaluate to terms to WHNF, e.g. `caseCon`
2. Make decisions based on the "representability" of types, e.g. `inlineNonRep`
Since the evaluator and type translator are bottoming for the Default instance.

Comment (martijnbastiaan) [reply clash-lib/tests/Test/Clash/Rewrite.hs:127]: They'd error out almost immediately, so I'm not too worried. I'll add a warning anyway though!

File: clash-lib/src/Clash/Normalize/Transformations.hs (hunk 1 above)
Comment (martijnbastiaan) [reply clash-lib/src/Clash/Normalize/Transformations.hs:2585]: True, that should be fine!
