### PR TITLE
Fix ordering issues in Manifest files (#2325, #2334)

### LINKED ISSUE #2325: Varying(!) sort order for transitive dependencies in manifest
Our source says:
https://github.com/clash-lang/clash-compiler/blob/f3e962be3588f2b85f07ab266ee21390c9b11fdc/clash-lib/src/Clash/Driver/Manifest.hs#L163-L170

At first I thought this TODO was outdated and we do a reverse topo sort now. Then, it turned out we do both (I here you gasping "but that is impossible!"... hold on).

The following source:
```haskell
module DepSort where

import Clash.Prelude

type T = Unsigned 8 -> Unsigned 8

f :: T
f = g . h
{-# NOINLINE f #-}
{-# ANN f (defSyn "f") #-}

g :: T
g = h . j
{-# NOINLINE g #-}
{-# ANN g (defSyn "g") #-}

h :: T
h = (+ 5)
{-# NOINLINE h #-}
{-# ANN h (defSyn "h") #-}

j :: T
j = (+ 10)
{-# NOINLINE j #-}
{-# ANN j (defSyn "j") #-}
```

gives a reverse topo sort:
```json
    "dependencies": {
        "transitive": [
            "DepSort.j",
            "DepSort.h",
            "DepSort.g"
        ]
    },
```

but splitting these functions into separate source files

<details><summary>like this</summary>

`DepSortF.hs`:
```haskell
module DepSortF where

import Clash.Prelude

import DepSortG
import DepSortH

f :: Unsigned 8 -> Unsigned 8
f = g . h
{-# NOINLINE f #-}
{-# ANN f (defSyn "f") #-}
```

`DepSortG.hs`:
```haskell
module DepSortG where

import Clash.Prelude

import DepSortH
import DepSortJ

g :: Unsigned 8 -> Unsigned 8
g = h . j
{-# NOINLINE g #-}
{-# ANN g (defSyn "g") #-}
```

`DepSortH.hs`:
```haskell
module DepSortH where

import Clash.Prelude

h :: Unsigned 8 -> Unsigned 8
h = (+ 5)
{-# NOINLINE h #-}
{-# ANN h (defSyn "h") #-}
```

`DepSortJ.hs`:
```haskell
module DepSortJ where

import Clash.Prelude

j :: Unsigned 8 -> Unsigned 8
j = (+ 10)
{-# NOINLINE j #-}
{-# ANN j (defSyn "j") #-}
```

</details>

gives us a topological sort!
```json
    "dependencies": {
        "transitive": [
            "DepSortG.g",
            "DepSortJ.j",
            "DepSortH.h"
        ]
    },
```

🤔

### LINKED ISSUE #2334: Manifest: wrong file order for include files
The following code:
```haskell
module FileOrder where

import Clash.Explicit.Prelude

topEntity ::
  Clock System ->
  Reset System ->
  Signal System Int ->
  Signal System Int ->
  Signal System Int ->
  Signal System Int
topEntity clk rst = assert clk rst "FileOrder"
{-# NOINLINE topEntity #-}
```
has the following manifest (VHDL):
```json
[...]
    "files": [
        {
            "name": "topEntity.sdc",
            "sha256": "13d4c1aafcc09a84d81d3b60d513cb901384a10e27e5a5a16572a600f15895f3"
        },
        {
            "name": "FileOrder_topEntity_types.vhdl",
            "sha256": "d02c6454a42e980254dbe81ffbdbaa1199419a1f9e1dcfca374692415139d3f1"
        },
        {
            "name": "topEntity.vhdl",
            "sha256": "e90c47000d5d18b95d9d11d375eb94693b67c49cf16a7fa493d541ff31d5bea7"
        },
        {
            "name": "topEntity_slv2string_2F58399B7F4E729C.vhdl",
            "sha256": "a94cf66fcd9f744ef94d77d5c4619960cbbacf140f8254b12cc2ee7e31bcf7b2"
        }
    ],
```

The file list is supposed to be sorted:
```haskell
  , fileNames :: [(FilePath, ByteString)]
    -- ^ Names and hashes of all the generated files for the @TopEntity@. Hashes
    -- are SHA256.
    --
    -- This list is reverse topologically sorted. I.e., a component might depend
    -- on any component listed before it, but not after it.
```
and we really want that as well. However, `topEntity.vhdl` depends on `topEntity_slv2string_....vhdl` which is listed after it.

I tried to fix this in https://github.com/clash-lang/clash-compiler/tree/topo-sort but it didn't work and I currently don't have the time to investigate. If you're working on this, feel free to (force) push to that branch and make it your own.

### PR DESCRIPTION
**Pull request by martijnbastiaan**
Fixes #2325

Fixes #2334

## Still TODO:

  - [x] Write a changelog entry (see changelog/README.md)
  - [x] Check copyright notices are up to date in edited files
  - [x] Write tests
  - [x] Update Vivado TCL - it doesn't need to call `update_compile_order` anymore.

### CODE REVIEW

**Review by DigitalBrains1 — COMMENTED** [review]
Thanks so much for fixing this!

I wonder if there is still some way to get files wrongly sorted. I had a whole manifesto in the commit msg for my attempt:
```markdown
We don't track dependency information for include files and memory
files. Include files are generated from
`Clash.Netlist.BlackBox.Types.bbIncludes` or YAML/JSON `includes` keys,
and memory files are generated from `~TEMPLATE` holes in the primitive
template language. We should actually track these dependencies to
maintain a proper reverse topological sort order in our manifest files.
However, this commit makes the problem less severe. We used to list
these include and memory files last in the list, but it is extremely
likely that the HDL file that caused the include/memory file to be
generated depends on it. So by listing them first instead of last, we
fix the sort order for the common case that the include/memory files
_themselves_ do not depend on anything else.

To be precise, we sort the include files after the memory files because
it is probably difficult to impossible to construct a memory file that
depends on an include file, but the reverse is easily achieved.
```

What could happen, I think, is that a primitive can reference another HDL file (because it refers to something that is generated in a separate HDL file). And if that primitive generates an include file that also references that HDL file, you'd want the include file to be in between the two HDL files in the dependency sort.

So maybe we still need a little warning somewhere that not every conceivable dependency is sorted, because that would require us to group HDL files and include files as they come to life rather than first listing all include files.

I had this FIXME in `clash-lib/src/Clash/Driver.hs` line 483:
```haskell
-- FIXME: We should track dependencies of `mfiles` and `dfiles` and
-- maintain the proper topological sort of all these.
```

**Comment by DigitalBrains1** [comment]
Now that `update_compile_order` is gone, you could try to enable all the tests that currently says "Vivado segfaults" to see if that is still the case. Because a different compile order might actually avoid whatever dumb thing Vivado is trying to do when it segfaults.

Ah, also: you can re-enable the "Parameters" test (`tests/Main.hs` line 365 and further), because that one was plagued by `update_compile_order` being crappy. This PR closes issue #2266 !

**Comment by martijnbastiaan** [comment]
> Ah, also: you can re-enable the "Parameters" test (tests/Main.hs line 365 and further), because that one was plagued by update_compile_order being crappy. This PR closes issue https://github.com/clash-lang/clash-compiler/issues/2266 !

Done, that works now. The others still segfault unfortunately.

**Comment by martijnbastiaan** [comment]
Also, manifesto added to the relevant commit.

**Review by christiaanb — APPROVED** [review]

File: tests/Main.hs [hunk 1]
```diff
@@ -367,7 +367,7 @@ runClashTest = defaultMain $ clashTestRoot
           --
```
Comment (DigitalBrains1) [inline tests/Main.hs:367]: This comment also needs to go

Comment (DigitalBrains1) [reply tests/Main.hs:367]: Wow I thought CI would take a while, it was done in under 32 minutes?

Comment (martijnbastiaan) [reply tests/Main.hs:367]: ah flip, you're right.

Comment (martijnbastiaan) [reply tests/Main.hs:367]: > 12 jobs for
[fix-2325-2334](https://gitlab.com/clash-lang/clash-compiler/-/commits/fix-2325-2334)
in 18 minutes and 50 seconds

GitLab :-). GHA usually takes longer, but it was feeling generous today!
