### PR TITLE
BiSignal tests look through Annotate

### LINKED ISSUE #2472: Annotate and BiSignal don't work together
When using `Annotate` to attach attributes to a `BiSignalIn`, it gets incorrectly declared as `input`. Example (comment out the Annotate lines to see the correct inout declaration):

```
module BiSigBug where

import Clash.Prelude
import Clash.Annotations.SynthesisAttributes

-- BiSignalIn must be present at the top level.
-- Putting it inside a multifield record caused the assign to drive an internal wire. 
type FtdiIO dom = "FTDI_D" ::: BiSignalIn 'Floating dom 8
                  `Annotate` 'StringAttr "LOC" "P1, P2, P4, N5, P5, M6, N6, M7"
                  `Annotate` 'StringAttr "IOSTANDARD" "LVTTL"
                  -- FIXME: Annotations break BiSignal in Clash 1.6.4!

topEntity
  :: Clock System -- -> Reset System -> Enable System
  -> FtdiIO System -> BiSignalOut 'Floating System 8
topEntity clk io
  = withClockResetEnable clk rst en $ writeToBiSignal io (pure out)
  where
    out = Nothing :: Maybe (BitVector 8)
    rst = unsafeToReset $ pure False -- resetGen
    en = enableGen
```

### PR DESCRIPTION
**Pull request by christiaanb**
Fixes #2472

## Still TODO:

  - [x] Write a changelog entry (see changelog/README.md)
  - [x] Check copyright notices are up to date in edited files

### CODE REVIEW

File: tests/shouldwork/Signal/BiSignal/T2472.hs [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+import qualified Prelude as P
+import System.Environment (getArgs)
+import System.FilePath ((</>))
+
+-- BiSignalIn must be present at the top level.
+-- Putting it inside a multifield record caused the assign to drive an internal wire.
+type FtdiIO dom = "FTDI_D" ::: BiSignalIn 'Floating dom 8
+                  `Annotate` 'StringAttr "LOC" "P1, P2, P4, N5, P5, M6, N6, M7"
+                  `Annotate` 'StringAttr "IOSTANDARD" "LVTTL"
+                  -- FIXME: Annotations break BiSignal in Clash 1.6.4!
```
Comment (DigitalBrains1) [inline tests/shouldwork/Signal/BiSignal/T2472.hs:16]: Could you remove this line? It's confusing if we ever look at this test later :-)

**Comment by DigitalBrains1** [comment]
So does this also fix an independent issue with the size of the port not being rendered or does that _only_ occur in this combination? Because if it's independent, I think it should have a changelog entry as well.

**Comment by christiaanb** [comment]
It's independent. I'll add an additional entry.
