### PR TITLE
Unroll primitives for splittable types

### LINKED ISSUE #1606: Error with Vectors of Clock Reset and Enable
I encountered a runtime error in Clash when trying to synthesize VHDL for a larger project and managed to recreate it with this example. Trying to synthesize `functionA` causes the list-index operator (`Prelude.!!`) to be called with an index that is too large. The offending `!!` is in  the `ArgGen` case of `Clash.Netlist.BlackBox.Util.renderTag` in `clash-lib`. Meanwhile `functionB` can be synthesized, and `functionC` fails with a slightly more informative error.

Is it a normal usage of Clash to pass around Clock, Reset, and Enable signals explicitly like this as the results of functions?

```haskell
{-# LANGUAGE NoImplicitPrelude     #-}
module Test where

import Clash.Prelude

data CRE = CRE (Clock System) (Reset System) (Enable System)

{-# ANN functionA (defSyn "FunctionA") #-}
{-# ANN functionB (defSyn "FunctionB") #-}
{-# ANN functionC (defSyn "FunctionC") #-}

functionA
    :: Clock System
    -> Reset System
    -> Enable System
    -> Vec 2 (Signal System Bool, CRE)
functionA = \ c r e ->
  let
    term   = CRE c r e
    vec    = term :> term :> Nil
    result = fmap (\a -> (pure True, a)) vec
  in
    result 

functionB
    :: Clock System
    -> Reset System
    -> Enable System
    -> Vec 2 CRE
functionB = \ c r e ->
  let
    term   = CRE c r e
    result = term :> term :> Nil
  in
    result

functionC
    :: Clock System
    -> Reset System
    -> Enable System
    -> Vec 2 CRE
functionC = \ c r e ->
  let
    term   = CRE c r e
    vec    = term :> term :> Nil
    result = fmap id vec
  in
    result
```

### PR DESCRIPTION
**Pull request by christiaanb**
Fixes #1606

### CODE REVIEW

File: clash-lib/src/Clash/Core/Util.hs [hunk 1]
```diff
@@ -601,3 +651,59 @@ sccLetBindings =
...
+-- | Make a case-decomposition that extracts a field out of a (Sum-of-)Product type
+mkSelectorCase
+  :: HasCallStack
+  => MonadUnique m
+  => String -- ^ Name of the caller of this function
+  -> InScopeSet
+  -> TyConMap -- ^ TyCon cache
+  -> Term -- ^ Subject of the case-composition
+  -> Int -- n'th DataCon
+  -> Int -- n'th field
```
Comment (leonschoorl) [inline clash-lib/src/Clash/Core/Util.hs:664]:
```suggestion
  -> Int -- ^ n'th field
```

File: clash-lib/src/Clash/Core/Util.hs [hunk 2]
```diff
@@ -601,3 +651,59 @@ sccLetBindings =
...
+
+-- | Make a case-decomposition that extracts a field out of a (Sum-of-)Product type
+mkSelectorCase
+  :: HasCallStack
+  => MonadUnique m
+  => String -- ^ Name of the caller of this function
+  -> InScopeSet
+  -> TyConMap -- ^ TyCon cache
+  -> Term -- ^ Subject of the case-composition
+  -> Int -- n'th DataCon
```
Comment (leonschoorl) [inline clash-lib/src/Clash/Core/Util.hs:663]:
```suggestion
  -> Int -- ^ n'th DataCon
```

**Review by leonschoorl — APPROVED** [review]
LGTM
