### PR TITLE
Fix `ANN TestBench` documentation

### LINKED ISSUE #1750: TestBench annotation confusion
There seems to be some confusion about the direction of the TestBench annotation.
Is it:
1. an annotation on a `Synthesize`d binder pointing to its testbench
2. an annotation on a testbench pointing to the thing that it is testing

The [current docs](https://hackage.haskell.org/package/clash-prelude-1.4.0/docs/Clash-Annotations-TopEntity.html#v:TestBench) state:

> Tell what binder is the TestBench for a Synthesize-annotated binder.

Not very clear.
But luckily there is also an example:
> ..., f has a Synthesize annotation, and g is the HDL test bench for f.
> ```haskell
> f = ...
> {-# ANN f (defSyn "f") #-}
> {-# ANN f (TestBench 'g) #-}
> 
> g :: Signal Bool
> g = ...
> ```
This is option 1.
This work, and clash will create HDL output for both `f` and `g`, but it will produce a warning:
```
Clash: Compiling TestNames.g
Clash: Normalization took 0.001s
[WARNING] Dubious primitive instantiation for Clash.Explicit.Testbench.tbClockGen: Clash.Signal.Internal.tbClockGen is not synthesizable! (disable with -fclash-no-prim-warn)
Clash: Netlist generation took 0.000s
Clash: Compiling TestNames.f
Clash: Normalization took 0.001s
Clash: Netlist generation took 0.000s
```

If we try option 2:
```haskell
f = ...
{-# ANN f (defSyn "f") #-}

g :: Signal Bool
g = ...
{-# ANN g (TestBench 'f) #-}
```
This also work, clash will also generate HDL files for both `f` and `g`, but this time the netlist code actually considers g to be a testbench and suppresses the `tbClockGen` warning: 
```
Clash: Compiling TestNames.g
Clash: Normalization took 0.001s
Clash: Netlist generation took 0.000s
Clash: Compiling TestNames.f
Clash: Normalization took 0.001s
Clash: Netlist generation took 0.000s
Clash: Total compilation took 0.957s
```

### PR DESCRIPTION
**Pull request by DigitalBrains1**
The documentation had it backwards, the `TestBench` annotation goes on
the test bench, not on the device under test.

Fixes #1750

## Still TODO:

  - [x] Write a changelog entry (see changelog/README.md)
  - [x] Check copyright notices are up to date in edited files

### CODE REVIEW

**Comment by alex-mckenna** [comment]
Why the `backport-1.4` @martijnbastiaan? Do you want another 1.4.x release, or can we upload new documentation on hackage without needing a new release?

**Comment by martijnbastiaan** [comment]
Oh just because it was an easy fix and the issue has been known for a while :sweat:.

> or can we upload new documentation on hackage without needing a new release?

Yes!

**Review by alex-mckenna — APPROVED** [review]

**Review by martijnbastiaan — APPROVED** [review]

File: clash-prelude/src/Clash/Annotations/TopEntity.hs [hunk 1]
```diff
@@ -206,21 +206,24 @@ See the documentation of 'Synthesize' for the meaning of all its fields.
...
-g = ...
+myTestBench :: Signal System Bool
+myTestBench = ...
+{\-\# NOINLINE myTestBench \#-\}
+{\-\# ANN myTestBench (TestBench \'entityBeingTested) \#-\}
 @
 
+The 'TestBench' annotation actually already implies a 'Synthesize' annotation on
+the device under test, so the 'defSyn' in the example could have been omitted.
+It will still need the @NOINLINE@ annotation, though.
```
Comment (leonschoorl) [inline clash-prelude/src/Clash/Annotations/TopEntity.hs:226]: I wonder if we should document this sort of semi-magic behaviour.
I think I agree with [Martijn](https://github.com/clash-lang/clash-compiler/issues/1750#issuecomment-814147942) that we might want to remove this (at some point).
And if it's not documented as a feature, it feel like it's easier to remove.

Comment (DigitalBrains1) [reply clash-prelude/src/Clash/Annotations/TopEntity.hs:226]: I rather think we should warn the user about this rather surprising aspect, and if we replace the functionality by an `isTestBench` annotation, we _really_ need to warn the user explicitly about this change in the Changelog as well as the Haddock documentation. Otherwise people might get very confused why the HDL generation suddenly changes when they add or remove a `TestBench` annotation.

For instance, the following source:
```haskell
module TB where

import Clash.Prelude

f :: Signal System (Unsigned 8) -> Signal System (Unsigned 8)
f = id
{-# NOINLINE f #-}

g :: Signal System Bool
g = (f 5) .==. 5
{-# NOINLINE g #-}
{-# ANN g (TestBench 'f) #-}

h :: Signal System (Unsigned 8) -> Signal System (Unsigned 8)
h = f
{-# NOINLINE h #-}
```

can lead to:
```
$ clash -Wall --vhdl TB -main-is h
[...]
$ ls vhdl/
TB.f  TB.h
```

whereas if we remove that `TestBench` annotation from g (or change it to the proposed `isTestBench`), we suddenly get:
```
clash -Wall --vhdl TB -main-is h
[...]
$ ls -R vhdl/
vhdl/:
TB.h

vhdl/TB.h:
clash-manifest.json  f.vhdl  h.vhdl  TB_h_types.vhdl
```

If we don't document this weird interaction (the user never even asked for `g`, what should its annotations matter?), I think we do our users a disservice.

File: clash-prelude/src/Clash/Annotations/TopEntity.hs [hunk 2]
```diff
@@ -208,19 +208,22 @@ See the documentation of 'Synthesize' for the meaning of all its fields.
...
+entityBeingTested :: ...
+entityBeingTested = ...
+{\-\# NOINLINE entityBeingTested \#-\}
+{\-\# ANN entityBeingTested (defSyn "entityBeingTested") \#-\}
+
 
-g :: Signal Bool
-g = ...
+myTestBench :: Signal System Bool
+myTestBench = ...
```
[the remark this answers is not in the document]
Comment (DigitalBrains1) [reply clash-prelude/src/Clash/Annotations/TopEntity.hs]: Excellent suggestion, thanks!

File: clash-prelude/src/Clash/Annotations/TopEntity.hs (hunk 1 above)
Comment (martijnbastiaan) [reply clash-prelude/src/Clash/Annotations/TopEntity.hs:226]: Like @leonschoorl I feel a bit meh about this whole semi-magic behavior, but I think that bolsters the need for documenting it. It's probably best to add a comment that we don't really recommend leaving out `defSyn`. (We already discussed this IRL, but I thought I'd post it here because Leon is out-of-office.)

Comment (DigitalBrains1) [reply clash-prelude/src/Clash/Annotations/TopEntity.hs]: We've been discussing this in the office, and have decided on documenting it _but_ recommending against it explicitly.
